- source/reference/mongosync.txt
New PR to make update to https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/6/ (due to vacation)
> DOCSP-22730 mongosync cli ref v2

- source/reference/mongosync.txt
[DOCSP-22730 Jira](https://jira.mongodb.org/browse/DOCSP-22730)
* [Staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22730-mongosync/reference/mongosync/)
* [Build Log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6287c19355f596c31d74c808)
> DOCSP-22730 mongosync CLI Reference

- source/faq.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22673-Create-faq-page/faq/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-22673)
> DOCSP-22673 Create FAQ page

- source/includes/api/requests/start.sh
- source/includes/api/responses/success.sh
- source/reference.txt
- source/reference/api.txt
- source/reference/api/start.txt
JIRA: [DOCSP-22948](https://jira.mongodb.org/browse/DOCSP-22948)
Staged: [start endpoint](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22948-b/reference/api/start/)
Source material: [google doc](https://docs.google.com/document/d/1KbEk-mTRSp2fuxCscMhONmcZA19RoP5MwtfgYo3OUug/edit#heading=h.eo3j3ql5t5gp)
> (DOCSP-22948): start endpoint

- source/includes/api/facts/no-body-parameters.rst
- source/includes/api/requests/resume.sh
- source/reference/api.txt
- source/reference/api/pause.txt
- source/reference/api/resume.txt
JIRA: [DOCSP-22950](https://jira.mongodb.org/browse/DOCSP-22950)
Staged: [resume endpoint](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22950/reference/api/resume/)
Source material: [google doc](https://docs.google.com/document/d/1KbEk-mTRSp2fuxCscMhONmcZA19RoP5MwtfgYo3OUug/edit#heading=h.dxhfelnjfkj8)
> (DOCSP-22950): resume endpoint

- snooty.toml
> DOCSP-23055 fix version number

- snooty.toml
- source/connecting/atlas-to-atlas.txt
- source/includes/fact-install-past-mongosync.rst
- source/includes/step-update-path-windows.rst
- source/installation.txt
- source/installation/install-on-linux.txt
- source/installation/install-on-macos.txt
- source/installation/install-on-windows.txt
NOTE: In the interest of speed, sending this out for internal and external review at the same time.
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23092-create-windows-install-page/installation/install-on-windows/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23092)
> DOCSP-23092 create windows install page

- source/includes/fact-mongodb-version.rst
- source/reference.txt
- source/reference/limitations.txt
NOTE: In the interest of time, sending this to internal and external review together.
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22998-create-limitations-page/reference/limitations/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-22998)
> DOCSP-22998 create limitations page

- config/redirects
Staging links don't work properly to test URL redirects, but here's the code
[STAGING](https://docs-mongodborg-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23089-create-redirect/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23089)
> DOCSP-23089 create top level redirect

- snooty.toml
- source/includes/limitations-warning.rst
- source/index.txt
- source/reference/api.txt
- source/reference/limitations.txt
- source/release-notes/0.9.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-23112)
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23112-limitations-updates/reference/limitations/)
> DOCSP-23112 limitations updates

- source/reference.txt
- source/release-notes/0.9.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23114-mvp-tweaks/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23114)
> DOCSP-23114 mvp tweaks

- source/quickstart.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-23125)
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23125-broken-link/quickstart/)
> DOCSP-23125 broken link

- source/reference/mongosync.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23119-consistency-guarantees/reference/mongosync/#consistency)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23119)
> DOCSP-23119 consistency guarantees

- source/installation/install-on-macos.txt
*Not reviewed due to MDBWorld* 
[JIRA](https://jira.mongodb.org/browse/DOCSP-23122)
> DOCSP-23122 macos file type

- source/includes/fact-atlas-roles.rst
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DCOSP-23084-link-to-reverse-v0.9.0/connecting/atlas-to-atlas/#roles)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23084)
> DOCSP-23084 add reverse link

- source/reference/limitations.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15440-dollar-prefixed-fields-v0.9.0/reference/limitations/#general-limitations)
[JIRA](https://jira.mongodb.org/browse/DOCS-15440)
> DOCS-15440 dollar prefixed fields

- source/reference/mongosync.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15126-conflict-resolution-for-sharded-clusters-v0.9.0/reference/mongosync/#sharded-clusters)
[JIRA](https://jira.mongodb.org/browse/DOCS-15126)
> DOCS-15126-conflict-resolution-during-sharding

- source/reference/limitations.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23597-remove-limitations-v1.0/reference/limitations/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23597)
> DOCSP-23597 Remove limitations

- source/faq.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15434-read-write-concern-v0.9.0/faq/#which-connection-string-options-does-mongosync-allow-)
[JIRA](https://jira.mongodb.org/browse/DOCS-15434)
> DOCS-15434 read write concern v0.9.0

- source/reference/mongosync.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23350-write-blocking-v0.9.0/reference/mongosync/#write-blocking)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23350)
> DOCSP-23350 write-blocking note

- source/reference/limitations.txt
[DOCS-15427](https://jira.mongodb.org/browse/DOCS-15427)
Adds section to C2C Limitations page on [System Collections](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15427-limitations/reference/limitations/#system-collections)
[Current Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62c86682f7f8bf6d9fd67546)
> DOCS-15427 System Collection Limitations

- source/includes/fact-write-blocking-requirement.rst
- source/reference/api/start.txt
- source/reference/mongosync.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23576-uri-actiontypes-v0.9.0/reference/api/start/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23576)
> DOCSP-23576 enableUserWriteBlock requirements

- source/faq.txt
- source/includes/fact-oplog-background.rst
- source/quickstart.txt
- source/reference.txt
- source/reference/limitations.txt
- source/reference/mongosync-states.txt
- source/reference/oplog-sizing.txt
* DOCSP-23262 oplog size
* DOCSP-23262 oplog window sizing
* Staging fixes
* Staging fixes
* Staging fixes
* Review feedback
> DOCSP-23262 BACKPORT

- source/reference.txt
[STAGING](https://docs-mongodborg-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23808-fix-TOC/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23808)
> DOCSP-23808 fix TOC

- source/reference.txt
- source/reference/failure-recovery.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23354-disaster-recovery-v1.0/reference/failure-recovery/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23354)
> DOCSP-23354 disaster recovery v1.0

- source/multiple-mongosyncs.txt
[DOCSP-23884](https://jira.mongodb.org/browse/DOCSP-23884)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23884-clarify-shard-docs/multiple-mongosyncs/#connect-the-mongosync-instances)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62d86bf6230aeb802ea5ba59) with no new errors.
> DOCSP-23884 clarify shard docs

- source/reference/limitations.txt
[DOCSP-23928](https://jira.mongodb.org/browse/DOCSP-23928)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23928-limitations-revisit/reference/limitations/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62d9856e230aeb802ecee591) with no new errors
> DOCSP-23928 Fixes relevant limitations

- source/reference/limitations.txt
[DOCSP-23933](https://jira.mongodb.org/browse/DOCSP-23933)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23933-limitations-active-dev/reference/limitations/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62d9c1c8230aeb802edabc47) with no errors
> DOCSP-23933 Removes paragraph

- source/reference.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-24823-config-page-appears-twice-v1.0/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-24823)
> DOCSP-24823 config appears twice

- source/reference/limitations.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15649-fix-limitation-wording-v1.0/reference/limitations/)
[JIRA](https://jira.mongodb.org/browse/DOCS-15649)
> DOCS-15649 fix limitations wording

- source/includes/fact-oplog-background.rst
- source/multiple-mongosyncs.txt
- source/quickstart.txt
- source/reference/limitations.txt
- source/reference/mongosync.txt
- source/reference/oplog-sizing.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-25489-harmonize-syncing-synchronizing-v.1/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-25489)
> DOCSP-25489-harmonize-syncing-synchronizing

- source/reference/limitations.txt
[Limitations](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-25657/reference/limitations/#general-limitations)
https://jira.mongodb.org/browse/DOCSP-25657
> DOCSP-25657 addresses limitations typo

- source/reference/limitations.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-27027-unique-nonUnique-limitation-v1.0/reference/limitations/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-27027)
> DOCSP-27027 unique and nonUnique indexes

- source/reference/limitations.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23839-queryable-encryption-typo/reference/limitations/#general-limitations) (last item in list)
[DOCSP-23839](https://jira.mongodb.org/browse/DOCSP-23839)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63b6fa1fdc742b91f20418c5)
> DOCSP-23839 Fixes typo

- source/reference/configuration.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-25803-improve-config-informatio-v1.0/reference/configuration/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-25803)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63b6fb13dc742b91f2045256)
> DOCSP-25803 add configuration linking

- source/reference/api/start.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15809-typo/reference/api/start/#sharding-parameters)
[Jira](https://jira.mongodb.org/browse/DOCS-15809)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63bee7bddc742b91f29a0374)
> DOCS-15809 Fixes typo

- source/includes/api/facts/includeNamespaces-syntax.rst
- source/includes/api/requests/start-filtered.sh
- source/includes/example-filter-collection-with-renaming.rst
- source/includes/example-filter-collection.rst
- source/includes/intro-start-api-example-intro.rst
- source/includes/limitations-filtering.rst
- source/reference.txt
- source/reference/api/start.txt
- source/reference/collection-level-filtering.txt
- source/reference/limitations.txt
[PAGE](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15709-collection-level-filter-v1.0/reference/collection-level-filtering/)
[LIMITATIONS](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15709-collection-level-filter-v1.0/reference/limitations/#collection-level-filtering)
[START API](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15709-collection-level-filter-v1.0/reference/api/start/)
[JIRA](https://jira.mongodb.org/browse/DOCS-15709)
> DOCS-15709 collection level filter

- source/release-notes.txt
- source/release-notes/1.2.txt
[Jira](https://jira.mongodb.org/browse/DOCS-15884)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15884-1.2-release-notes/release-notes/1.2/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63ebc7c2dcefe977976f244c)
> DOCS-15884 1.2 release notes

- source/quickstart.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15841-quickstart-and-like-topologies-v1.2/quickstart/#define-a-source-and-a-destination-cluster)
[JIRA](https://jira.mongodb.org/browse/DOCS-15841)
[build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63ee79b5dcefe97797fe7295)
> DOCS-15841 quickstart topology update

- source/faq.txt
Adds an FAQ entry covering slow operation warnings and what to do about them.
[FAQ](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28763-slow-op-warnings/faq/#what-if-i-see-a-slow-operation-warning-)
[DOCSP-28763](https://jira.mongodb.org/browse/DOCSP-28763)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=642c8222b49106a49863e403)
> DOCSP-28763 FAQ for slow operations warnings

- source/includes/fact-minimum-versions.rst
- source/reference/limitations.txt
- source/release-notes/1.2.txt
- source/release-notes/1.3.txt
Staging
[limitations](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29606-minimum-version-v1.0/reference/limitations/#general-limitations)
[release notes 1.3](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29606-minimum-version-v1.0/release-notes/1.3/)
[release notes 1.2](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29606-minimum-version-v1.0/release-notes/1.2/)
[jira](https://jira.mongodb.org/browse/DOCSP-29606)
[build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=645121f27efd2382b3381275)
> DOCSP-29606 minimum version

- source/reference.txt
- source/release-notes.txt
- source/release-notes/1.0.txt
- source/release-notes/1.1.txt
- source/release-notes/1.2.txt
- source/release-notes/1.3.txt
- source/release-notes/1.4.txt
[Rel notes](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-30223-1.4.0-release-notes/release-notes/1.4/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-30223)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6489d28a67a273b81629ba14)  Updated 2023-06-14
> DOCSP-30223 1.4.0 release notes

- source/reference/limitations.txt
[staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15615-remove-limitation/reference/limitations/)
[jira](https://jira.mongodb.org/browse/DOCS-15615)
[build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64932c64423952aeb910294c)
> DOCS-15615 remove limitation

- source/release-notes/1.4.txt
[staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-30916-release-date/release-notes/1.4/)
[jira](https://jira.mongodb.org/browse/DOCSP-30916)
[build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64945305423952aeb95c82fc)
> DOCSP-30916 release date

- source/release-notes/1.4.txt
[staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-30934-release-notes-1.4.1/release-notes/1.4/)
[jira](https://jira.mongodb.org/browse/DOCSP-30934)
[build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6494c6d7423952aeb98f45d3)
> DOCSP-30934 release notes

- source/facets.toml
- source/reference/facets.toml
- source/release-notes/facets.toml
Hey @sarah-olson-mongodb!  Here's the facet.toml files for the cluster-to-cluster sync repo.  Please merge if it looks good to you!
Thank you!
Sarah
> DOCSP-32483 programmatic tagging script for c2c repo

- source/includes/table-permissions-self-hosted.rst
Updating mongosync permissions table 
https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-32457/reference/permissions/#self-managed-clusters
https://jira.mongodb.org/browse/DOCSP-32457
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65007b7424fcc731b46b15d7
> DOCSP 32457 mongosync permissions table update

- source/reference/limitations.txt
- source/reference/versioning.txt
- source/release-notes/1.6.txt
Release Notes for 1.6.0.
* [Other Notes](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-32917-1.6-rn/release-notes/1.6/#other-notes)
[DOCSP-32917](https://jira.mongodb.org/browse/DOCSP-32917)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65037a8524fcc731b4421421)
> DOCSP-32917 mongosync 1.6 Release Notes

- source/reference/limitations.txt
- source/release-notes/1.6.txt
Fixes minor formatting issue on Limitations pages.
[Limitations](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-33393-fixes-limitation-format/reference/limitations/)
[DOCSP-33393](https://jira.mongodb.org/browse/DOCSP-33393)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65246012885de6b26beee8f5)
> DOCSP-33393 Fixes minor formatting issue

- source/multiple-mongosyncs.txt
Removes balancer warning per eng request. 
https://preview-mongodbmdbashley.gatsbyjs.io/cluster-sync/DOCS-16368-remove-balancer-warning/multiple-mongosyncs/
https://jira.mongodb.org/browse/DOCS-16368
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=652eadbd673b813c8f5cef63
> Removes balancer warning

- source/release-notes/1.7.txt
Release notes for mongosync 1.7.
[RN](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-33758-1.7-release-notes/release-notes/1.7/)
[DOCSP-33758](https://jira.mongodb.org/browse/DOCSP-33758)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65300d02673b813c8fc287ff)
> DOCSP-33758 mongosync 1.7 Release Notes

- config/redirects
- snooty.toml
- source/includes/in-dev.rst
- source/index.txt
- source/release-notes/1.8.txt
Added an include to be used for upcoming documentation, as well as empty 1.8 release notes.
> Adds upcoming information to master branch in preparation for publishing upcoming

- source/includes/capped-collection-size.rst
- source/reference/disaster-recovery.txt
Add small update for capped collections.
JIRA
https://jira.mongodb.org/browse/DOCSP-33784
STAGE
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/cluster-sync/DOCSP-33784-capped-remediation/reference/disaster-recovery/#use-mongosync-for-disaster-recovery
BUILD LOG
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654589b2bd8a7a9579acc235
> DOCSP-33784-capped-remediation

- source/release-notes/1.7.txt
Release notes for mongosync 1.7.1
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-34250/release-notes/1.7/#patch-releases
https://jira.mongodb.org/browse/DOCSP-34250
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654bfcc55b686d6bd9834455
> DOCSP-34250 release notes 1.7.1

- source/release-notes/1.7.txt
Ports [#184](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/184) to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654e47d55b686d6bd91823de)
> DOCSP-34250 release notes 1.7.1 (#184)

- source/reference/limitations.txt
update mongosync limitations with community
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-33217/reference/limitations/#mongodb-community-edition
https://jira.mongodb.org/browse/DOCSP-33217
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654bf30f5b686d6bd97f3e77
> DOCSP-33217 update mongosync limitations with community

- source/reference/limitations.txt
Ports #183 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6553c62f5b686d6bd948db15)
> DOCSP-33217 update mongosync limitations with community (#183)

- source/includes/fact-write-blocking-enable.rst
- source/reference/mongosync.txt
Ports #182 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6553c71b5b686d6bd9493f0a)
> DOCS-16422 clarifying write blocking behavior (#182)

- source/reference/versioning.txt
Updates `mongosync` version compatibility table w/ MDB v7.0 compatibility 
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-34238-mongosync-version-compat/reference/versioning/#mongodb-server-version-compatibility-and-support
https://jira.mongodb.org/browse/DOCSP-34238
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655397285b686d6bd937fffa
> DOCSP-34238 Mongosync Version Compatibility

- source/reference/versioning.txt
Ports #186 to c2c v1.7 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6555110d5b686d6bd9a5da7b
> DOCSP-34238 Mongosync Version Compatibility (#186)

- source/includes/api/requests/start-filtered.sh
- source/reference/collection-level-filtering.txt
- source/reference/collection-level-filtering/filter-regex.txt
- source/release-notes/1.6.txt
Ports #187 to c2c v1.7
BUILD:https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65551eb15b686d6bd9ac7fdf
> DOCSP-34081 collectionsRegex typos (#187)

- source/multiple-mongosyncs.txt
Ports #192 to c2c v1.7 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655630065b686d6bd9f54b29
> DOCSP-33886 Remove 'Stop Balancer on Destination' Step (#192)

- source/reference/mongosync.txt
Port #188 to v1.7
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655631865b686d6bd9f5d139
> DOCSP-30831 mongosync Commit Behavior Clarification (#188)

- source/includes/cross-version-sync.rst
- source/includes/fact-minimum-fcv.rst
- source/includes/fact-minimum-server-version-support.rst
- source/quickstart.txt
- source/reference/limitations.txt
- source/reference/versioning.txt
Ports #200 to C2C v1.7 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655d0f3113dc9d16ead89c0b
> DOCSP-33885 Fix Server Version Requirement References (#200)

- source/faq.txt
- source/reference/mongosync.txt
adding info about mongosync errors and resilience
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-33265/reference/mongosync/#resilience
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-33265/faq/#do-i-need-to-terminate-migration-early-if-i-see-error-or-failure-logs-
https://jira.mongodb.org/browse/DOCSP-33265
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655cc0715b686d6bd97998c9
> DOCSP 33265 Resilience of mongosync

- source/faq.txt
- source/includes/fact-minimum-fcv.rst
Ports #205 to v1.7 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6566631a7a5cb5fef5f76d64
> DOCSP-34646 Fix 404 fCV Link (#205)

- source/reference/mongosync.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=656777957a5cb5fef53c2015)
> DOCSP-32408 Fixes --cluster1 reference - Backport to v1.7

- source/reference/mongosync.txt
Ports #203 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65679b497a5cb5fef54c9daa)
> DOCSP-38407 read and write concern info (#203)

- source/multiple-mongosyncs.txt
Ports #211 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=656a0c027a5cb5fef5eaa50a)
> DOCSP-33786 clarify number of mongosync instances (#211)

- source/quickstart.txt
fixing quickstart build error
https://jira.mongodb.org/browse/DOCSP-34814
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657097aa7a5cb5fef56e6ad5
> DOCSP-34814 fixing build error

- source/includes/fact-connection-strings-atlas.rst
- source/includes/fact-connection-strings.rst
- source/includes/read-preference-connection-string.rst
- source/reference/mongosync.txt
Ports #213 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6578a3177a5cb5fef5693298)
> DOCSP-34133 adding read preference info to connection strings (#213)

- source/installation/install-on-macos.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657b320a7a5cb5fef5270385)
> DOCSP-35742 Fixes Mac Extraction (#221)

- source/release-notes/1.2.txt
Ports #220 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657b73037a5cb5fef53efa32)
> DOCSP-28526 1.2 release notes clarification (#220)

- source/reference/mongosync.txt
Ports #224 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6580790f7a5cb5fef54be5ea)
> DOCSP-35053 removing duplicate sections (#224)

- source/faq.txt
- source/includes/fact-oplog-background.rst
Ports #218 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6580798f7a5cb5fef54c0ef8)
> DOCSP 33887 Updating oplog sizing section (#218)

- source/connecting/atlas-to-atlas.txt
- source/connecting/onprem-to-atlas.txt
- source/includes/fact-atlas-require-indexes-limitation.rst
- source/reference/limitations.txt
Ports #232 to v1.7 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65983afadcc0144a516b5049
> DOCSP-33161 Disable Require Indexes Option on Atlas (#232)

- source/reference/mongosync.txt
Ports #230 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=659ffef9dcc0144a5144c2db)
> DOCSP 29155 adding sort and uuids to mongosync page (#230)

- source/reference/api/commit.txt
- source/reference/disaster-recovery.txt
Ports #222 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a0280fdcc0144a515346e5)
> DOCSP 28174 adding info to commit page (#222)

- source/faq.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a06b77dcc0144a516e33b1)
> DOCSP-33581 TTL Index Support (#173) - Backport to v1.7

- source/quickstart.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a17269dcc0144a51b301f1)
> DOCSP-31136 Adds --logPath to Quickstar (#225) - Backport to v1.7

- source/includes/api/tables/progress-response.rst
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b96dc06b2f17c95a0502ed)
> DOCSP-27579 lagTimeSecond fix (#245) -Backport to v1.7

- source/includes/collections/behavior-capped-collections.rst
- source/reference/api/start.txt
- source/reference/limitations.txt
Ports #178 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65bbf5466b2f17c95ace0e0f)
> DOCSP 33890 updating mongosync limitations bullets (#178)

- source/reference/limitations.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65bc0f306b2f17c95ada198f)
> DOCSP-33399 role limitation (#248) - Backport to v1.7

- source/includes/table-permissions-self-hosted.rst
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65bd5b796b2f17c95a4094d6)
> Docsp 34408 req roles v1.7

- source/includes/table-permissions-self-hosted.rst
Quick fix to build error in C2C
* [Staging](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-36268-fix-build/connecting/onprem-to-onprem/#roles)
* [DOCSP-36268](https://jira.mongodb.org/browse/DOCSP-36268)
* [2024-02-02](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65bd6c396b2f17c95a49754e)
> DOCSP-36268 Fixes build issues

- source/reference/api/start.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c161a56b2f17c95a20c294)
> DOCSP-23551 Adds reversible note (#247) - Backport to v1.7

- source/reference/mongosync-states.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ccf9b6cbcd269fa53169a1)
> DOCSP-25143 Adds /reverse to COMMITTED state (#258) - Backport to v1.7

- source/includes/example-connect.rst
- source/includes/fact-connection-strings-atlas.rst
- [JIRA](https://jira.mongodb.org/browse/DOCSP-25670)
- Stage
- https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-25670/connecting/onprem-to-atlas/
- https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-25670/connecting/atlas-to-atlas/
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c66bc66b2f17c95a9b08ac)
> DOCSP-25670 Remove ports from SRV connection strings

- snooty.toml
- source/includes/fact-verification.rst
- source/multiple-mongosyncs.txt
- source/quickstart.txt
- source/reference.txt
- source/reference/api/commit.txt
- source/reference/verification.txt
- source/reference/verification/count.txt
- source/reference/verification/hash.txt
- source/reference/verification/verifier.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d6544a7111165982ef8530)
> DOCSP-34813 Data Verification (#241) - Backport to v1.7

- source/includes/api/facts/multiple-mongosync-endpoints.rst
- source/multiple-mongosyncs.txt
- source/reference/api/commit.txt
- source/reference/api/pause.txt
- source/reference/api/resume.txt
- source/reference/api/reverse.txt
- source/reference/api/start.txt
Ports #264 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d75929711116598234df57)
> DOCSP-32690 multiple mongosync endpoint note (#264)

- source/quickstart.txt
Ports #275 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e2258411db7b04279da656)
> DOCSP-23924 reformatting quickstart (#275)

- snooty.toml
- source/reference/versioning.txt
Clarifies supported version for mongosync.
[Currently Supported Versions](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-32186-c2c-version/reference/versioning/#currently-supported-versions)
[DOCSP-32186](https://jira.mongodb.org/browse/DOCSP-32186)
* [2024-02-27](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65de5da57111165982e80429)
* [2024-03-01](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e227f311db7b04279ef2b1)
> DOCSP-32186 Version Information

- source/includes/fact-api-endpoint.rst
- source/reference/api/commit.txt
- source/reference/api/pause.txt
- source/reference/api/progress.txt
- source/reference/api/resume.txt
- source/reference/api/reverse.txt
- source/reference/api/start.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660c37cb3a5920a2914b74d2)
> DOCSP-32282 API Security (#149)

- source/reference/limitations.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-38184)
- [Stage](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-38184/reference/limitations/#sharded-clusters)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660d60663a5920a29196b65e) (contains errors and warnings nor introduced by changes in this PR)
> DOCSP-38184 Indicate that any reshardCollection operations are disallowed

- source/includes/fact-log-rotation-usr1-signal.rst
- source/reference/logging.txt
- source/reference/mongosync.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-36500)
- Stage:
- https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-36500/reference/logging/#log-to-file
- https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-36500/reference/mongosync/
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661024603a5920a29173f6a9)
> DOCSP-36500 Document SIGUSR1 handling for Mongosync

- source/includes/fact-write-blocking-enable.rst
- source/reference/api/commit.txt
- source/reference/disaster-recovery.txt
Ports #301 to v1.7 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66266c55b67dbf804a2203f8
> DOCSP-38839 Source Cluster Read Only Behavior (#301)

- snooty.toml
- source/includes/fact-minimum-server-version-support.rst
- source/release-notes/1.7.txt
Forward port for https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/303
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6627ce2eb67dbf804a7ea97a
> DOCSP-38889 update min supported server versions (#303)

- source/release-notes/1.7.txt
Fixes release date for 1.7.2.
* [RN](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-39089-release-date-fix/release-notes/1.7/#1.7.2-release)
[DOCSP-39089](https://jira.mongodb.org/browse/DOCSP-39089)
* [2024-04-29](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=662ff28eb67dbf804a57e9fb)
> DOCSP-39089 Fixes release date for 1.7.2

- source/release-notes/1.7.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66311844b67dbf804aa10d7e)
> DOCSP-39089 Fixes release date for 1.7.2 (#308)

- source/reference/limitations.txt
Ports #312 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66392f76b67dbf804a7d655e)
> DOCSP-39095 adding atlas search indexes limitation (#312)

- source/reference/mongosync.txt
Ports #311 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66393c42b67dbf804a825fbe)
> DOCSP 39098  Recommend limiting DDL operations during a sync (#311)

- source/reference/limitations.txt
- source/reference/versioning.txt
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663a4924b67dbf804abef030
https://preview-mongodbianfmongodb.gatsbyjs.io/cluster-sync/DOCSP-38018/reference/limitations/
> DOCSP-38018 Add Note Mongosync Cannot Mid Upgrade

- source/faq.txt
Add faq regarding fatal errors.
https://preview-mongodbjocelynmendez1.gatsbyjs.io/cluster-sync/DOCSP-38696/faq/#what-should-i-do-if-mongosync-returns-a-fatal-error-
https://jira.mongodb.org/browse/DOCSP-38696
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6627d712b67dbf804a816d15
> DOCSP-38696 Add faq regarding fatal errors

- source/reference/api/reverse.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664e497ecf5bec1c29c962a3)
> DOCSP-39211 reverse update (#320)

- snooty.toml
- source/reference/beta-program.txt
Adds a notice for users that they must accept the disclaimer when they first run the `mongosync` beta binary. 
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-40106-beta-disclaimer/reference/beta-program/#get-started
https://jira.mongodb.org/browse/DOCSP-40106
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=666b52b1ebce19f314aa11d2
> DOCSP-40106 C2C Beta Disclaimer

- source/reference/mongosync.txt
Clarify the supported patch release versions on the mongosync reference page
- [mongosync](https://preview-mongodbjeffallenmongo.gatsbyjs.io/cluster-sync/DOCSP-40657/reference/mongosync/)
https://jira.mongodb.org/browse/DOCSP-40657
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66742d61ebce19f31487023b
> (DOCSP-40657): Clarify patch releases for version support

- source/reference/mongosync.txt
* (DOCSP-40657): Clarify patch releases for version support
* typo
Build log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66745e08ebce19f31495e986
> (DOCSP-40657): Clarify patch releases for version support (#330)

- source/reference/beta-program.txt
- source/reference/beta-program/destinationDataHandling.txt
Add description for destination handling.
JIRA:
https://jira.mongodb.org/browse/DOCSP-38289
Build log:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6675c8a8ebce19f314eed08f
Staging:
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/cluster-sync/DOCSP-38289-add-description-destination-handling/reference/beta-program/#beta-features
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/cluster-sync/DOCSP-38289-add-description-destination-handling/reference/beta-program/destinationDataHandling/#std-label-c2c-beta-destination-data-handling
> DOCSP-38289-add-description-destination-handling

- source/reference/limitations.txt
Add views limitation per JIRA. Kept it minimal to avoid the weeds, which might be subject to many changes.
JIRA:
https://jira.mongodb.org/browse/DOCSP-40749
Build log:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6675f7e8ebce19f314fc3fcd
Staging:
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/cluster-sync/DOCSP-40749-many-to-one-limitation/reference/limitations/#multiple-source-sync-limitations
> DOCSP-40749-many-to-one-limitation

- source/includes/critical-warning-text.rst
- source/includes/release-notes/REP-4274.rst
- source/includes/release-notes/REP-4294.rst
- source/release-notes/1.1.txt
- source/release-notes/1.2.txt
- source/release-notes/1.3.txt
- source/release-notes/1.4.txt
- source/release-notes/1.5.txt
- source/release-notes/1.6.txt
- source/release-notes/1.7.txt
* (DOCSP-40128): v1.7.3 release notes
* more updates
* fix
* fix
* address review comments
Backports PR #336.
> (DOCSP-40128): v1.7.3 release updates (#326)

- source/reference/disaster-recovery.txt
- Wording updates to disaster recovery page + updated table.
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-40742-disaster-recovery/reference/disaster-recovery/
https://jira.mongodb.org/browse/DOCSP-40742
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=668c54b9fb8bd13b8438e58c
> DOCSP-40742-disaster-recovery-page-updates

- source/reference/disaster-recovery.txt
Ports #340 to v1.7 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=668c58d4fb8bd13b8439bfc7
> DOCSP-40742-disaster-recovery-page-updates (#340)

- source/faq.txt
- source/includes/fact-restart-resume-delay.rst
- source/reference/api/progress.txt
- source/reference/api/resume.txt
- source/reference/mongosync-states.txt
- source/release-notes.txt
- source/release-notes/1.7.txt
Ports #343 to v1.7 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66954009fb8bd13b8412fe86
> DOCSP-40138-Mongosync-Delay-After-Resume-Restart (#343)

- source/includes/live-upgrade.rst
DOCSP-41355 live upgrade updates
https://jira.mongodb.org/browse/DOCSP-41355
https://preview-mongodbjmdmongo.gatsbyjs.io/cluster-sync/DOCSP-41355/reference/versioning/#live-upgrade
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6697d7cb26eba79552b83355
> DOCSP-41355 live upgrade updates

- source/reference/limitations.txt
Ports #348 to v1.7 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=669809da26eba79552ca99c3
> DOCSP-40105-storageEngine-limitation (#348)

- source/reference/api/start.txt
Fixes a bug in the userWriteBlocking custom role creation code example. 
Ticket: https://jira.mongodb.org/browse/DOCSP-40471
Staging: https://preview-mongodbmdbashley.gatsbyjs.io/cluster-sync/DOCSP-40471-code-bugfix/reference/api/start/
Build Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66981fd826eba79552d536ea
> DOCSP-40471: fix code typo in v1.7

- source/reference/mongosync-states.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=669ec6d526eba7955238ef3e)
> DOCS-16652 Adds Reversing State (#282) - Backport to v1.7

- source/reference/api/reverse.txt
Backports #355 to v1.7
Build log https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66a01cae26eba795528f159a
> added reversing descr (#355)

- snooty.toml
- source/about-mongosync.txt
- source/includes/fact-connection-strings-atlas.rst
- source/includes/fact-connection-strings-onprem.rst
- source/includes/fact-connection-strings.rst
- source/index.txt
- source/quickstart.txt
- source/reference.txt
- source/reference/configuration.txt
- source/reference/cutover-process.txt
- source/reference/disaster-recovery.txt
- source/reference/logging.txt
- source/reference/mongosync.txt
- source/reference/mongosync/mongosync-behavior.txt
- source/reference/telemetry.txt
- source/reference/verification.txt
- source/reference/verification/verifier.txt
- source/reference/versioning.txt
- source/release-notes/1.0.txt
- Created the "mongosync Behavior" page and took behavior information from "mongosync" page
- Created a new "mongosync" page that follows the [Information Type Style Guide ](https://www.mongodb.com/docs/meta/style-guide/information-types/prototypes/reference/)
- Fixed ref's accordingly
- Tried to reduce repeated links
mongosync Behavior: https://preview-mongodbsonderdonkmdb.gatsbyjs.io/cluster-sync/DOCSP-41323/reference/mongosync/mongosync-behavior/
mongosync: https://preview-mongodbsonderdonkmdb.gatsbyjs.io/cluster-sync/DOCSP-41323/reference/mongosync/ 
Link changes:
-[About mongosync (Learn More)](https://preview-mongodbsonderdonkmdb.gatsbyjs.io/cluster-sync/DOCSP-41323/about-mongosync/#learn-more)
-[Connecting mongosync](https://preview-mongodbsonderdonkmdb.gatsbyjs.io/cluster-sync/DOCS …
> DOCSP-41323 made behavior page

- snooty.toml
- source/about-mongosync.txt
- source/includes/fact-connection-strings-atlas.rst
- source/includes/fact-connection-strings-onprem.rst
- source/index.txt
- source/quickstart.txt
- source/reference.txt
- source/reference/configuration.txt
- source/reference/disaster-recovery.txt
- source/reference/logging.txt
- source/reference/mongosync.txt
- source/reference/mongosync/mongosync-behavior.txt
- source/reference/telemetry.txt
- source/reference/verification.txt
- source/reference/verification/verifier.txt
- source/reference/versioning.txt
- source/release-notes/1.0.txt
Backports #356 for v1.7
Build log https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66aa7036824f175afd74a5cd
> DOCSP-41323 made behavior page (#356)

- source/release-notes/1.7.txt
Ports #367 to v1.7 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66ad44ef824f175afd26716d
> DOCSP-41855-1.7.3-bug-typo (#367)

- snooty.toml
- source/includes/abc-migration-intro.rst
- source/includes/api/requests/start-namespace-remap.sh
- source/includes/beta-feature.rst
- source/includes/beta-program-intro.rst
- source/includes/destinationDataHandling-introduction.rst
- source/includes/document-filtering-intro.rst
- source/includes/document-filtering-limitations.rst
- source/includes/fact-valid-namespace-remap.rst
- source/includes/many-to-one-cluster.rst
- source/includes/migration-name-limitation.rst
- source/includes/namespace-remapping-intro.rst
- source/includes/opts/migrationName.rst
- source/includes/orr-intro.rst
- source/includes/table-beta-compatibility.rst
- source/index.txt
- source/quickstart.txt
- source/reference.txt
- source/reference/api/start.txt
- source/reference/beta-program.txt
- source/reference/beta-program/abc-migration.txt
- source/reference/beta-program/destinationDataHandling.txt
- source/reference/beta-program/document-filtering.txt
- source/reference/beta-program/many-to-one.txt
- source/reference/beta-program/namespace-remapping.txt
- source/reference/beta-program/orr.txt
- source/reference/configuration.txt
- source/reference/disaster-recovery.txt
- source/reference/mongosync.txt
- source/release-notes/1.8.txt
Merging c2c beta feature branch
STAGING: https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/master/reference/beta-program/
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66b2632d824f175afd281c56
> C2C Beta Docs  (#370)

- snooty.toml
- source/index.txt
- source/reference/beta-program.txt
- source/release-notes.txt
- source/release-notes/1.8.txt
- source/release-notes/1.9.txt
- Create 1.9.txt under release notes
- Update snooty variables for v1.9 (upcoming) and v1.8 (current)
- Swapped out constants where not needed
- [c2c landing page
](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-42301-1.9-in-dev/#cluster-to-cluster-sync)
- [1.9 release notes](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-42301-1.9-in-dev/release-notes/1.9/)
https://jira.mongodb.org/browse/DOCSP-42301
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66b51e2583839571177207b3
> DOCSP-42301-1.9-in-dev

- source/reference/limitations.txt
Ports #380 to v1.8
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bce60a8383957117163762
> DOCSP-37061-mongosync-timestamp-limitation (#380)

- source/reference/beta-program.txt
Swap out existing HELP link for support for users to access beta binaries
- See [Slack thread for more context](https://mongodb.slack.com/archives/C02SQPJHQ85/p1722627425522949)
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-42528-beta-program-help/reference/beta-program/#get-started
https://jira.mongodb.org/browse/DOCSP-42528
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bce807838395711716e04d
> DOCSP-42528 Swap out Support Link

- source/reference/beta-program.txt
Ports #381 to v1.8 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bcf0368383957117190ba1
> DOCSP-42528 Swap out Support Link (#381)

- source/reference/api/commit.txt
Ports #388 to v1.8 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bf84688e811ae67277a1e2
> DOCSP-35777 Source Writes After Commit (#388)

- source/includes/warn-option-cluster-password-visibility.rst
- source/reference/mongosync.txt
Ports #387 to v1.8
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bfb9cd8e811ae6728adcee
> DOCSP-23892 adds warning for cluster options v1.8 backport (#387)

- source/includes/warn-option-cluster-password-visibility.rst
- source/reference/mongosync.txt
Ports #387 to v1.8
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bfba6b8e811ae6728afdf5
> DOCSP-23892 adds warning for cluster options v1.7 backport (#387)

- source/includes/fact-minimum-server-version-support.rst
- source/reference/beta-program/document-filtering.txt
- source/reference/beta-program/namespace-remapping.txt
- source/release-notes/1.7.txt
Ports #385 to v1.8 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c34d388e811ae6721f1b11
> DOCSP-39103 Minimum Server Versions (#385)

- source/includes/opts/loadlevel-warning.rst
Update loadLevel documentation warning to address bottlenecks
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-37310/reference/mongosync/#std-option-mongosync.--loadLevel
https://jira.mongodb.org/browse/DOCSP-37310
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bf640d8e811ae6726d8cbb
> DOCSP-37310 update loadLevel warning

- source/faq.txt
- Add new faq section regarding duplicate key errors
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-37071-duplicate-key-errors/faq/#what-if-i-see-a-lot-of-duplicate-key-errors-in-the-logs-
https://jira.mongodb.org/browse/DOCSP-37071
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bf5e828e811ae6726b708c
> DOCSP-37071 Duplicate Key Error FAQ

- source/faq.txt
Ports #389 to v1.8 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c4ba4b8e811ae67272ef5a
> DOCSP-37071 Duplicate Key Error FAQ (#389)

- source/reference/beta-program/destinationDataHandling.txt
Ports #398 to v1.8 
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c4d0f38e811ae67279a9ad
> DOCSP-42728 ignorePreExistingNamespaces (#398)

- source/includes/opts/loadlevel-warning.rst
Ports #390 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c76b4340f3e3c873462d15)
> DOCSP-37310 update loadLevel warning (#390)

- source/connecting.txt
- source/index.txt
- source/installation.txt
- source/reference.txt
- source/reference/beta-program.txt
- source/reference/collection-level-filtering.txt
- source/reference/mongosync.txt
- source/reference/verification.txt
- source/release-notes.txt
- source/topologies.txt
Refactoring ToC with the [new style guide ](https://www.mongodb.com/docs/meta/style-guide/style/toc-labels/)
https://deploy-preview-406--docs-cluster-to-cluster-sync.netlify.app
https://jira.mongodb.org/browse/DOCSP-43305
https://app.netlify.com/sites/docs-cluster-to-cluster-sync/deploys/66e04e5354bdfd0008804ae9
> DOCSP-43305-ToC-refactor

- source/connecting.txt
- source/index.txt
- source/installation.txt
- source/reference.txt
- source/reference/beta-program.txt
- source/reference/collection-level-filtering.txt
- source/reference/mongosync.txt
- source/reference/verification.txt
- source/release-notes.txt
- source/topologies.txt
> DOCSP-43305-ToC-refactor (#406)

- source/includes/table-beta-compatibility.rst
- source/reference/beta-program.txt
Add pre-6.0 server version support to beta docs: 
- Feature compatibility matrix 
- Beta features table
- [Beta Features](https://deploy-preview-410--docs-cluster-to-cluster-sync.netlify.app/reference/beta-program/)
- [Feature Compatibility Matrix + footnote](https://deploy-preview-410--docs-cluster-to-cluster-sync.netlify.app/reference/beta-program/#feature-compatibility-matrix)
https://jira.mongodb.org/browse/DOCSP-43393
> DOCSP-43393 Older Version Support

- source/includes/table-beta-compatibility.rst
- source/reference/beta-program.txt
> DOCSP-43393 Older Version Support (#410)

- source/includes/api/tables/progress-response.rst
- source/reference/api/commit.txt
- source/reference/api/start.txt
* DOCSP-42974-c2c-nested-components
* build errors
> DOCSP-42974-c2c-nested-components (#416)

- source/faq.txt
"denable" -> "enable" on faq page
https://deploy-preview-421--docs-cluster-to-cluster-sync.netlify.app/faq/#can-i-perform-reads-or-writes-to-my-destination-cluster-while-mongosync-is-syncing-
https://jira.mongodb.org/browse/DOCSP-43752
> DOCSP-43752-faq-typo

- source/faq.txt
> DOCSP-43752-faq-typo (#421)

- source/includes/table-permissions-self-hosted.rst
Replaced dbAdmin with dbAdminAnyDatabase on the mongosync required permissions page.
https://deploy-preview-427--docs-cluster-to-cluster-sync.netlify.app/reference/permissions/
https://jira.mongodb.org/browse/DOCSP-43389
> DOCSP-43389-required-roles

- source/reference/api/reverse.txt
> DOCSP-43492-blocking-link-reverse-sync (#426)

- source/reference/beta-program.txt
> DOCSP-43751-mongosync-beta-reverse (#424)

- source/includes/table-permissions-self-hosted.rst
> DOCSP-43389-required-roles (#427)

- source/connecting.txt
- source/includes/fact-connect-intro.rst
- source/includes/mongosync-and-oidc.rst
- source/reference.txt
- source/reference/authentication.txt
- source/reference/mongosync.txt
- source/release-notes/1.8.txt
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* DOCSP-43265-OIDC-program
* …
> DOCSP-43265-OIDC-program BACKPORT

- source/release-notes/1.8.txt
Release notes for C2C 1.8.1.
[RN](https://deploy-preview-430--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.8/#1.8.1-release)
[DOCSP-43827](https://jira.mongodb.org/browse/DOCSP-43827)
> DOCSP-43827 1.8.1 RN

- source/reference/api/commit.txt
- source/reference/cutover-process.txt
Clarifies the cutover process.
* [Finalize Cutover](https://deploy-preview-408--docs-cluster-to-cluster-sync.netlify.app/reference/cutover-process/)
* [commit intro](https://deploy-preview-408--docs-cluster-to-cluster-sync.netlify.app/reference/api/commit/) 
[DOCSP-43294](https://jira.mongodb.org/browse/DOCSP-43294)
> DOCSP-43294 Cutover Clarifications

- source/reference/authentication.txt
Additional fast follow updates per comments in https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/419 as part of https://jira.mongodb.org/browse/DOCSP-44349.
Staging:
https://deploy-preview-437--docs-cluster-to-cluster-sync.netlify.app/reference/authentication/
> DOCSP-44349-OIDC-additions

- source/reference/limitations.txt
* DOCSP-44635-global-cluster-limit
* *
> DOCSP-44635-global-cluster-limit (#444)

- source/includes/api/tables/progress-response.rst
- source/reference/configuration.txt
- source/reference/mongosync.txt
- source/reference/telemetry.txt
> DOCSP-35726-version-notes (#441)

- source/reference/limitations.txt
> DOCSP-44876-rolling-index-limitation (#457)

- source/includes/rolling-build-limitation.rst
- source/reference/limitations.txt
- source/reference/mongosync/mongosync-behavior.txt
> DOCSP-45041-adding-rolling-limitation-to-behavior (#462)

- source/faq.txt
> DOCSP-44977 notes index build behavior during sync (#463)

- source/includes/beta-feature-non-admonition.rst
- source/reference/api/start.txt
Removes "important" nested admonition
Edits "Importants" in the documentFilter and namespaceRemap rows of the[ Start Request Body Parameters](https://deploy-preview-469--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/#request-body-parameters)
https://jira.mongodb.org/browse/DOCSP-44795
> DOCSP-44795-remove-important-admonitions

- source/includes/beta-feature-non-admonition.rst
- source/reference/api/start.txt
> DOCSP-44795-remove-important-admonitions (#469)

- source/index.txt
Change mongosync top level ToC label to "About mongosync"
https://deploy-preview-473--docs-cluster-to-cluster-sync.netlify.app
https://jira.mongodb.org/browse/DOCSP-45163
> DOCSP-45163-mongosync-toc-label

- source/index.txt
> DOCSP-45163-mongosync-toc-label (#473)

- source/includes/api/requests/start-no-verifier.sh
- source/includes/api/responses/progress.json
- source/includes/fact-verifier-beta-unsupport.rst
- source/includes/fact-verifier-buildIndexes.rst
- source/includes/fact-verifier-limitations.rst
- source/includes/fact-verifier-memory.rst
- source/includes/fact-verifier-unsupported.rst
- source/includes/opts/acceptDisclaimer.rst
- source/reference/api/reverse.txt
- source/reference/api/start.txt
- source/reference/configuration.txt
- source/reference/mongosync.txt
- source/reference/mongosync/mongosync-behavior.txt
- source/reference/verification.txt
- source/reference/verification/embedded.txt
- source/release-notes/1.9.txt
Documents the embedded verifier for C2C v1.9.
* [Verification - Embedded Verifier](https://deploy-preview-339--docs-cluster-to-cluster-sync.netlify.app/reference/verification/#std-label-c2c-verify-with-embedded-verifier)
* [Verify with Embedded Verifier](https://deploy-preview-339--docs-cluster-to-cluster-sync.netlify.app/reference/verification/embedded/)
* [Limitations](https://deploy-preview-339--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/#embedded-verifier)
* [verificationMode Parameter](https://deploy-preview-339--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/#request-body-parameters)
* [Verifier Behavior](https://deploy-preview-339--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/#embedded-verifier)
* ["verification" /progress …
> DOCSP-35686 Embedded Verifier

- source/release-notes/1.9.txt
- Adds release date to 1.9 release notes 
Note: The [stable release page](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/release-notes/) was updated in a previous PR, but those changes seemed to not make it into the last deploy. Re-deployed the docs, so that should already be live.
https://deploy-preview-498--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.9/#1.9.0-release
https://jira.mongodb.org/browse/DOCSP-45413
> DOCSP-45413-1.9-release-date

- source/reference.txt
- source/reference/api/reverse.txt
- source/reference/cutover-process.txt
- source/reverse-sync.txt
- source/topologies/multiple-mongosyncs.txt
> DOCSP-45263-adding-reverse-tutorial (#481)

- source/reference.txt
- source/reference/api/reverse.txt
- source/reference/cutover-process.txt
- source/reverse-sync.txt
- source/topologies/multiple-mongosyncs.txt
> DOCSP-45263-adding-reverse-tutorial (#481) 

- source/reference/verification.txt
Backports https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/526 to v1.9 
[DOCSP-45308](https://jira.mongodb.org/browse/DOCSP-45308)
- https://deploy-preview-529--docs-cluster-to-cluster-sync.netlify.app/reference/verification/
> (DOCSP-45308) Backport to v1.9: [c2c] add note on how to verify shard keys (#526)

- source/includes/table-permissions-atlas.rst
Remove backup as a required role for Atlas 
https://deploy-preview-551--docs-cluster-to-cluster-sync.netlify.app/reference/permissions/#atlas-clusters
https://jira.mongodb.org/browse/DOCSP-46461
> DOCSP-46461-remove-backup-as-required-role

- snooty.toml
Update note to change "Command Line Database Tools" to "mongosync".
- https://deploy-preview-562--docs-cluster-to-cluster-sync.netlify.app/
- https://deploy-preview-562--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/
https://jira.mongodb.org/browse/DOCSP-46767
> DOCSP-46767-update-mongosync-nongenuine-note

- source/includes/table-permissions-self-hosted.rst
> DOCSP-46396 removed backup (#556)

- source/includes/opts/disableVerification.rst
- source/reference/configuration.txt
- source/reference/mongosync.txt
Adds `disableVerification` option and setting.
> **NOTE:** Release note on this feature covered by [DOCSP-45958](https://jira.mongodb.org/browse/DOCSP-45958).
* [--disableVerification](https://deploy-preview-561--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/#std-option-mongosync.--disableVerification)
* [disableVerification](https://deploy-preview-561--docs-cluster-to-cluster-sync.netlify.app/reference/configuration/#mongodb-setting-disableVerification)
[DOCSP-46429](https://jira.mongodb.org/browse/DOCSP-46429)
> DOCSP-46429 disableVerification

- .backportrc.json
Update backport config to add v1.10 to list of branches 
N/A
https://jira.mongodb.org/browse/DOCSP-46924
> DOCSP-46924 Update C2C Backport file

- source/installation/install-on-linux.txt
Adds RHEL 9 to the support list.
[Platform Support](https://deploy-preview-575--docs-cluster-to-cluster-sync.netlify.app/installation/install-on-linux/#platform-support)
[DOCSP-45645](https://jira.mongodb.org/browse/DOCSP-45645)
> DOCSP-45645 RHEL 9 Support

- source/installation/install-on-linux.txt
> DOCSP-45645 RHEL 9 Support (#575)

- source/faq.txt
- source/reference/mongosync/mongosync-behavior.txt
* DOCSP-47219-midsync-reads
* active voice
* internal feedback
* MVK feedback
> DOCSP-47219 Midsync Reads FAQ (#612)

- source/includes/fact-oplog-background.rst
> DOCSP-47126 edited oplog background fact (#609)

- source/includes/fact-minimum-server-version-support.rst
- Bumped minimum supported version numbers
[mongosync compatibility](https://deploy-preview-626--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/#compatibility)
https://jira.mongodb.org/browse/DOCSP-47212
> DOCSP-47212 Bumped compatibility version numbers

- source/reference/cutover-process.txt
> DOCSP-45442 (#621)

- source/reference/beta-program-private/orr.txt
added a note about ORR compatibility with embedded verification
Note for reviewer: Is more elaboration needed in this note? 
https://deploy-preview-634--docs-cluster-to-cluster-sync.netlify.app/reference/beta-program-private/orr/#behavior
[DOCSP-46946](https://jira.mongodb.org/browse/DOCSP-46946)
> DOCSP-46946 added note about ORR and embedded verification

- source/reference/beta-program-private/orr.txt
> DOCSP-46946 added note about ORR and embedded verification (#634)

- source/reference/verification.txt
- source/reference/verification/custom-manual.txt
> DOCSP-46301-clean-verify-data (#617)

- source/includes/table-permissions-atlas.rst
Fix typo in permission name and also link to the privilege definition.
[User Permissions](https://deploy-preview-658--docs-cluster-to-cluster-sync.netlify.app/reference/permissions/#user-permissions)
https://jira.mongodb.org/browse/DOCSP-48417
> DOCSP-48417-writeBlocking-permission-typo

- source/reference/api/start.txt
Reorder note on mongosync in [sharding parameters section of "start" page](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/api/start/#sharding-parameters). 
https://deploy-preview-672--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/#sharding-parameters
https://jira.mongodb.org/browse/DOCSP-48393
> DOCSP-48393-reorder-shardingEntries-note

- snooty.toml
Updates the Snooty `title` field for SEO.
[DOCSP-48290](https://jira.mongodb.org/browse/DOCSP-48290)
> DOCSP-48290 Snooty Title

- source/reference/live-upgrade.txt
Remove blurb about live updates
https://deploy-preview-716--docs-cluster-to-cluster-sync.netlify.app/reference/live-upgrade/
https://jira.mongodb.org/browse/DOCSP-48963
> DOCSP-48963-remove-live-upgrade-blurb

- source/release-notes/1.13.txt
1.13.1 Release
Backport to 1.13
https://deploy-preview-720--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.13/
> 1.13.1 Release
