mongodb/docs-cluster-to-cluster-sync

snooty.toml, source/index.txt
Note: I tried using the alias for the title in the snooty.toml file, but it doesn't appear to work there. Perhaps that's just a step too meta. 
[STAGING](https://docs-mongodborg-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22838-create-product-name-alias/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-22838)
=> DOCSP-22838 create product name alias

source/faq.txt, source/includes/api/requests/pause.sh, source/includes/api/tables/basic-response.rst, source/reference/api.txt, source/reference/api/pause.txt, source/reference/api/start.txt
Note for review - as part of this update I also added a "Requirement" section to indicate what state the tool must be in in order to send the request. I also applied this small formatting change to the `start` endpoint page.
JIRA: [DOCSP-22949](https://jira.mongodb.org/browse/DOCSP-22949)
Staged:
- [pause endpoint](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22949/reference/api/pause/)
- [start endpoint](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22949/reference/api/start/)
Source material: [google doc](https://docs.google.com/document/d/1KbEk-mTRSp2fuxCscMhONmcZA19RoP5MwtfgYo3OUug/edit#heading=h.dxhfelnjfkj8)
=> (DOCSP-22949): pause endpoint

source/includes/step-update-path.rst
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23077-fix-directory-structure/installation/install-on-linux/)
[JIRA]https://jira.mongodb.org/browse/DOCSP-23077)
=> DOCSP-23077 Directory structure has changed

source/reference/api/commit.txt, source/reference/api/pause.txt, source/reference/api/progress.txt, source/reference/api/resume.txt, source/reference/api/start.txt
Add copyable false options to "Request" (non example) and Response code blocks.
Staged:
- [start](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/copyable-false/reference/api/start/)
- [progress](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/copyable-false/reference/api/progress/)
- [pause](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/copyable-false/reference/api/pause/)
- [resume](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/copyable-false/reference/api/resume/)
- [commit](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/copyable-false/reference/api/commit/)
=> (DOCSP-23080): Add copyable false options

source/includes/api/tables/progress-response.rst, source/reference.txt, source/reference/mongosync-states.txt
New page describing the different states of the c2c utility.
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23020/reference/mongosync-states
=> (DOCSP-23020): sync states reference page

source/reference/mongosync-states.txt
Address feedback left on PR #26
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/sync-cleanup/reference/mongosync-states/
=> cleanup sync states page

source/reference/limitations.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15438-fle2-not-supported-v0.9.0/reference/limitations/)
[JIRA](https://jira.mongodb.org/browse/DOCS-15438)
=> DOCS-15438 fle2 not supported

source/reference/limitations.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15445-expireAfterSeconds-unsupported-v1.0/reference/limitations/)
[JIRA](https://jira.mongodb.org/browse/DOCS-15445)
=> DOCS-15445 expireAfterSeconds not supported

source/reference/mongosync.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23337-users-and-roles-synched-v0.9.0/reference/mongosync/#cluster-independence)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23337)
=> DOCSP-23337 users and roles not synched

source/includes/api/requests/start-reversible.sh
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23770-missing-backslash-v0.9.0/reference/api/start/#request-2)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23770)
=> DOCSP-23770 missing backslash

source/reference/limitations.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23312-index-limit-lower-v0.9.0/reference/limitations/#sharded-clusters)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23312)
=> DOCSP-23312 index limit lower by one

source/includes/api/responses/progress.json, source/includes/api/tables/progress-response.rst, source/reference/api/progress.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15470-add-canWrite-v1.0/reference/api/progress/)
[JIRA](https://jira.mongodb.org/browse/DOCS-15470)
=> DOCS-15470 add can write v1.0

source/connecting/onprem-to-onprem.txt, source/includes/fact-atlas-roles.rst, source/includes/fact-onprem-roles.rst, source/includes/fact-write-blocking-requirement.rst, source/reference/api/start.txt
[DOCSP-23785](https://jira.mongodb.org/browse/DOCSP-23785)
Staging:
* Updates [Requirements](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23785-auth-writeblock/reference/api/start/#requirements) for `start` API call with note about `bypassWriteBlockingMode` and example of how to create a custom role.
* Adds [Roles](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23785-auth-writeblock/connecting/onprem-to-onprem/#roles) section to On-Prem-to-On-Prem connections
* Moves Reverse Direction content in [On-Prem-to-Atlas](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23785-auth-writeblock/connecting/onprem-to-atlas/#roles) roles into an admonition to better highlight it. …
=> DOCSP-23785 auth writeblock

source/connecting/onprem-to-onprem.txt, source/includes/fact-onprem-roles.rst, source/includes/fact-write-blocking-requirement.rst, source/reference/api/start.txt
Backports to v1.0 branch.
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62d841f3230aeb802e9e66b8) with no new errors.
=> DOCSP-23785 auth writeblock - backport v1.0

source/reference/failure-recovery.txt, source/reference/limitations.txt
[DOCSP-23911](https://jira.mongodb.org/browse/DOCSP-23911)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23911-capped-collections/reference/limitations/#unsupported-collection-types) adds Capped collection line to v1.0
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62d97817230aeb802ecce4bc) with no new errors.
=> DOCSP-23911 Adds capped collections line

source/release-notes.txt, source/release-notes/1.0.txt
[DOCSP-23934](https://jira.mongodb.org/browse/DOCSP-23934)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23934-release-notes-1.0/release-notes/1.0/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62dac3b4230aeb802e0079f4) with no new errors.
=> DOCSP-23934 release notes 1.0

source/includes/fact-atlas-roles.rst
[DOCSP-23936](https://jira.mongodb.org/browse/DOCSP-23936)
Staging:
* [Atlas to Atlas](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23936-custom-typo/connecting/atlas-to-atlas/#roles)
* [On-prem to Atlas](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23936-custom-typo/connecting/onprem-to-atlas/#roles)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62e40083230aeb802e710ee5) with no new errors
=> DOCSP-23936 Fixes typo

source/includes/example-connect.rst
[DOCSP-23908](https://jira.mongodb.org/browse/DOCSP-23908)
Staging:
* [Atlas to Atlas](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23908-cluster-typo/connecting/atlas-to-atlas/#connect-the-source-and-destination-clusters-with-mongosync)
* [On-prem to On-prem](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23908-cluster-typo/connecting/onprem-to-onprem/#connect-the-source-and-destination-clusters-with-mongosync)
* [On-prem to Atlas](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23908-cluster-typo/connecting/onprem-to-atlas/#connect-the-source-and-destination-clusters-with-mongosync)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62e …
=> DOCSP-23908 Fixes typo

source/includes/example-connect.rst, source/multiple-mongosyncs.txt, source/quickstart.txt
JIRA
https://jira.mongodb.org/browse/DOCSP-23870
STAGE
https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23870-mongosync-atlas/connecting/atlas-to-atlas/#connect-the-source-and-destination-clusters-with-mongosync
NOTE
JIRA states:
"On the [Quickstart page](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/quickstart/#define-administrative-users), we mention the following:
"If the source cluster is hosted in Atlas, the user must have the Atlas admin role. The user must also be able to read the change stream for the cluster."
I was able to successfully run a mongosync with just the Atlas admin role for the source cluster. Do we need the second sentence? I found it a little confusing."
Jason comment:
Spoke with JIRA logger and we agreed to keep …
=> DOCSP-23870 mongosync atlas

source/includes/example-connect.rst
JIRA
https://jira.mongodb.org/browse/DOCSP-24022
STAGE
https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-24022-connection-string-mongosync/connecting/atlas-to-atlas/#connect-the-source-and-destination-clusters-with-mongosync
=> DOCSP-24022-connection-string-mongosync

source/reference/limitations.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-25519-uniqueness-of-id-v1.0/reference/limitations/#sharded-clusters)
The 'see for more information' link isn't live yet. It will work when [this PR](https://github.com/10gen/docs-mongodb-internal/pull/1933) in the server repo is merged. 
[JIRA](https://jira.mongodb.org/browse/DOCSP-25519)
=> DOCSP-25519 uniqueness of id

snooty.toml, source/index.txt, source/reference.txt, source/reference/limitations.txt, source/reference/versioning.txt
[VERSIONING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-25767-add-versioning-documentation-v1.0/reference/versioning/)
[INDEX PAGE](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-25767-add-versioning-documentation-v1.0/)
[LIMITATIONS](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-25767-add-versioning-documentation-v1.0/reference/limitations/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-25767)
=> DOCSP-25767 add versioning documentation v1.0

source/reference/limitations.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-26762-rapid-releases-not-supported-v1.0/reference/limitations/#general-limitations)
[JIRA](https://jira.mongodb.org/browse/DOCSP-26762)
=> DOCSP-26762 rapid releases not supported

source/includes/fact-atlas-roles.rst, source/includes/fact-reverse-sync-action-types.rst, source/quickstart.txt, source/reference/api/reverse.txt
[STAGING reverse](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-26789-duplicate-note-box-v1.0/reference/api/reverse/)
[STAGING sync notes](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-26789-duplicate-note-box-v1.0/quickstart/#synchronization-notes)
[STAGING atlas](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-26789-duplicate-note-box-v1.0/connecting/onprem-to-atlas/#roles)
[JIRA](https://jira.mongodb.org/browse/DOCSP-26789)
=> DOCSP-26789 duplicate note box

source/includes/api/requests/start-rs-shard.sh, source/reference/api/start.txt, source/reference/limitations.txt
Updates to `/start` endpoint:
* [Sharding Parameters](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15702-static-unlike-topologies/reference/api/start/#sharding-parameters)
* [RS->SC Example](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15702-static-unlike-topologies/reference/api/start/#example-3---start-sync-from-replica-set-to-sharded-cluster)
* Behavior Sections:
* [Shard Collections](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15702-static-unlike-topologies/reference/api/start/#shard-collections)
* [Supporting Indexes](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15702-static-unlike-topologies/reference/api/start/#supporting-in …
=> DOCS-15702 Static Unlike Topologies 

source/includes/fact-reverse-limitation.rst, source/multiple-mongosyncs.txt, source/reference/api/reverse.txt, source/reference/limitations.txt
STAGING
[multiple mongosync](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15881-sharding-m-to-n/multiple-mongosyncs/#configure-multiple-mongosync-instances)
[limitations](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15881-sharding-m-to-n/reference/limitations/#reversing)
[reverse](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15881-sharding-m-to-n/reference/api/reverse/)
[JIRA](https://jira.mongodb.org/browse/DOCS-15881)
Some missing info re: M -> N shard migrations
[build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63e6b243dcefe97797862a9c)
=> DOCS-15881 m to n sharding

source/includes/example-connect.rst, source/quickstart.txt
Fixes issue with `mongosync` initialization examples.  The `--cluster0` and `--cluster1` options take a MongoDB URL with commas separating each mongod instance in the cluster.  We split these out into new lines for readability, but this causes the shell to interpret additional mongod instances as commands rather than extensions of the option argument.
Inlining `--cluster0` and `--cluster1` arguments corrects the issue.
* [Connection Example](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23883-bad-example/connecting/atlas-to-atlas/#connect-the-source-and-destination-clusters-with-mongosync)
* [Quickstart Example](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-23883-bad-example/quickstart/#initialize-mongosync) …
=> DOCSP-23883 Fixes connection example

source/reference/limitations.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15937-typo/reference/limitations/#sharded-clusters)
[JIRA](https://jira.mongodb.org/browse/DOCS-15937)
Typo in parameter name
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=640b5b4c054271fb0ab001ac)
=> DOCS-15937 typo, line lengths

config/redirects
Redirects the unversioned pages to /current as requested and adds missing redirects for version flipping the release notes.
Note: if 0.9 is EOL'd and you would like it added to the Legacy site (rather than just labeling it Legacy), then please follow the   instructions here: https://wiki.corp.mongodb.com/display/DE/How+To%3A+Sunset+a+Version+of+Documentation
=> DOP-3535: correctly redirect old C2C docs

source/includes/limitations-filtering.rst, source/reference/collection-level-filtering.txt
Adds `mapReduce` to `$out` limitations.
* [Filtering with mapReduce & $out](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-27804-add-mapReduce/reference/collection-level-filtering/#filtering-with-mapreduce-and--out)
* [Limitations](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-27804-add-mapReduce/reference/collection-level-filtering/#limitations) (Changes made to last bullet point).
[DOCSP-27804](https://jira.mongodb.org/browse/DOCSP-27804)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6418d26cb070a41637f8721d)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=641b12bab070a41637727069) …
=> DOCSP-27804 add mapReduce Limitation

source/includes/collections/behavior-capped-collections.rst, source/includes/collections/behavior-system-collections.rst, source/reference/limitations.txt, source/reference/mongosync.txt, source/release-notes.txt, source/release-notes/1.2.txt, source/release-notes/1.3.txt
STAGING
[limitations](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28950-cappd-collections-v1.3/reference/limitations/#capped-collections)
[mongosync](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28950-cappd-collections-v1.3/reference/mongosync/#capped-collections)
[release notes](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28950-cappd-collections-v1.3/release-notes/1.3/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-28950)
[C2C] Support for Capped Collections
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=642f33c6b49106a498f99608)
=> DOCSP-28950 capped collections

source/includes/api/tables/progress-response.rst, source/includes/fact-write-blocking-check.rst, source/includes/fact-write-blocking-enable.rst, source/includes/fact-write-blocking-when.rst, source/reference/api/reverse.txt, source/reference/mongosync-states.txt, source/reference/mongosync.txt
STAGING
[/progress](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28691-when-to-write-to-dest-v1.2/reference/api/progress/#response)
[/reverse](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28691-when-to-write-to-dest-v1.2/reference/api/reverse/#requirements)
[mongosync](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28691-when-to-write-to-dest-v1.2/reference/mongosync/#write-blocking)
[mongosync states](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28691-when-to-write-to-dest-v1.2/reference/mongosync-states/#read-operations)
[JIRA](https://jira.mongodb.org/browse/DOCSP-28691)
[C2C] Users should not write to dst until canWrite is …
=> DOCSP-28691 when to write to destination cluster

source/reference/api/start.txt, source/release-notes/1.3.txt
Documents `buildIndexes` option for `/start`.
[`/start`](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-15946-index-toggle/reference/api/start/#request-body-parameters)
[DOCS-15946](https://jira.mongodb.org/browse/DOCS-15946)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=642dc337b49106a498a8c690)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=643485f1b49106a498eea137)
=> DOCS-15946 Documents buildIndexes option

source/includes/api/tables/progress-response.rst
Adds the `mongosyncID` and `coordinatorID` fields to the `/progress` output table.
[Response](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28806-coordinatorid/reference/api/progress/#response) (last two items on the table).
[DOCSP-28806](https://jira.mongodb.org/browse/DOCSP-28806)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6435a05bb49106a49829dd29)
=> DOCSP-28806 mongosyncID/coordinatorID return fields for /progress calls

source/release-notes/1.3.txt
Adds release notes for mongosync 1.3.0/
[RN](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28834-release-notes-1.3/release-notes/1.3/)
[DOCSP-28834](https://jira.mongodb.org/browse/DOCSP-28834)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64381b74b49106a498b489b7)
=> DOCSP-28834 release notes 1.3

source/includes/collections/behavior-capped-collections.rst
Fixed typo that read as "The maximum document size is 1PB" -> fixed to "the maximum **collection** size is 1PB"
https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29170-capped-collection-document-size-limit/reference/mongosync/#capped-collections
https://jira.mongodb.org/browse/DOCSP-29170
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6446e5c95f7a7fd956efb8a1
=> DOCSP-29170 Capped Collections Size Limit Typo

source/includes/opts/loadLevel.rst, source/reference/configuration.txt, source/reference/mongosync.txt, source/release-notes/1.4.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-29498
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29498-throttle-options/reference/mongosync/#std-option-mongosync.--loadLevel
https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29498-throttle-options/reference/configuration/#mongodb-setting-loadLevel
https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29498-throttle-options/release-notes/1.4/#set-cluster-workload-level
=> DOCSP-29498 throttle-options

source/includes/opts/disableTelemetry.rst, source/includes/opts/telemetry-statement.rst, source/reference/configuration.txt, source/reference/mongosync.txt, source/reference/telemetry.txt
[command line](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29449-add-telemetry/reference/mongosync/#std-option-mongosync.--disableTelemetry)
[config file](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29449-add-telemetry/reference/configuration/#mongodb-setting-disableTelemetry)
[telemetry](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29449-add-telemetry/reference/telemetry/#std-label-c2c-telemetry)
[JIRA](https://jira.mongodb.org/browse/DOCSP-29499) [REP] Add Telemetry to mongosync
( Replaces and expands [DOCSP-28563](https://jira.mongodb.org/browse/DOCSP-28563), [PR 122](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/122/) ) …
=> DOCSP-29449 add telemetry information

source/faq.txt, source/includes/fact-oplog-background.rst, source/reference/oplog-sizing.txt
Refactors Tim's recommendations for oplog sizing for C2C docs.
[DOCSP-29500](https://jira.mongodb.org/browse/DOCSP-29500)
* [FAQ Entry](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29500-oplog-sizing/faq/#should-i-increase-the-size-of-the-oplog-in-the-source-cluster-)
* [Intro](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-29500-oplog-sizing/reference/oplog-sizing/#oplog-sizing)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=648b78e1259a8493e5b36dda)
=> DOCSP-29500 Clarify oplog Sizing

source/faq.txt, source/includes/fact-oplog-background.rst, source/reference/oplog-sizing.txt
Reverts DOCSP-29500.
* [FAQ](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-30864-revert-oplog/faq/#should-i-increase-the-size-of-the-oplog-in-the-source-cluster-)
* [oplog Sizing](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-30864-revert-oplog/reference/oplog-sizing/)
[DOCSP-30865](https://jira.mongodb.org/browse/DOCSP-30864)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64921ee3259a8493e53604ca)
=> DOCSP-30865 - Revert Changes from DOCSP-29500

source/includes/sharding-warning.rst, source/multiple-mongosyncs.txt
Request for the addition of a warning and some steps for when syncing to a sharded destination cluster.
* [Intro Warning](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-31028-sharding-warning/multiple-mongosyncs/#use-mongosync-on-sharded-clusters)
* [Step: Stop Balancer](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-31028-sharding-warning/multiple-mongosyncs/#stop-the-balancer-on-the-destination)
* [Restart Balancer after commit](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-31028-sharding-warning/multiple-mongosyncs/#commit-synchronization-from--multiple-mongosync-instances)
[DOCSP-31028](https://jira.mongodb.org/browse/DOCSP-31028) …
=> DOCSP-31028 sharding warning

source/faq.txt, source/includes/fact-oplog-background.rst, source/includes/opts/verbosity.rst, source/reference/oplog-sizing.txt, source/release-notes.txt, source/release-notes/1.5.txt
* Adds release notes for 1.5.0.  
* Restores content on oplog sizing, reverted from 1.4.
* Updates verbosity defaults
* [RN](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-31391-1.5-release-notes/release-notes/1.5/)
* [Oplog Sizing intro](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-31391-1.5-release-notes/reference/oplog-sizing/)
* [verbosity defaults](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-31391-1.5-release-notes/reference/configuration/#mongodb-setting-verbosity)
[DOCSP-31391](https://jira.mongodb.org/browse/DOCSP-31391)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b80e9a87b3b3604604d84d)
* …
=> DOCSP-31391 1.5 release notes

source/includes/fact-oplog-background.rst
Fixes typo
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-31612-typo/reference/oplog-sizing/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64c000f587b3b36046df5aff)
=> DOCSP-31612 Fixes typo

source/reference/telemetry.txt
Adds notice that request bodies sent to the `/start` endpoint are sent as telemetry.
* [Telemetry](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-31307-start-telemetry/reference/telemetry/#data-collection)
* [DOCSP-31307](https://jira.mongodb.org/browse/DOCSP-31307)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e7bdb324fcc731b43b3e22)
=> DOCSP-31307 Adds /start API request body to telemetry list

source/includes/api/tables/progress-error-response.rst, source/includes/api/tables/progress-response.rst, source/reference/api/progress.txt
Fix the `progress` documentation to indicate that the error response is different from a successful completion.  Also,
modifies the response table to allow for better wrapping.
* [progress response](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-32048-process-clarification/reference/api/progress/#response)
* [DOCSP-32048](https://jira.mongodb.org/browse/DOCSP-32048)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64dcf85f67dbe910102ca0f8)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e4da3757e37806c5411521)
=> DOCSP-32048 process Error Response

source/includes/fact-mongodb-version.rst
The minimum supported MDB version for c2c is server 6.0.8.
https://jira.mongodb.org/browse/DOCSP-32574
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ed02b824fcc731b43eea17
- [Linux Version Requirements](https://preview-mongodbjeffallenmongo.gatsbyjs.io/cluster-sync/DOCSP-32574/installation/install-on-linux/#version-requirements)
- [macOS Version Requirements](https://preview-mongodbjeffallenmongo.gatsbyjs.io/cluster-sync/DOCSP-32574/installation/install-on-macos/)
- [Windows Version Requirements](https://preview-mongodbjeffallenmongo.gatsbyjs.io/cluster-sync/DOCSP-32574/installation/install-on-windows/#version-requirements)
=> (DOCSP-32574): Update minimum MDB version

source/includes/example-connect.rst, source/quickstart.txt, source/reference/mongosync.txt
Updated all `mongosync command` connection strings to use double quotes instead of single quotes. 
- [Quickstart](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-16353-windows-shell-quotes/quickstart/#initialize-mongosync)
- [Connect Two Atlas Clusters](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-16353-windows-shell-quotes/connecting/atlas-to-atlas/#:~:text=on%20one%20line%3A-,mongosync,-%5C)
- [Connect Two Self-Managed Clusters](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCS-16353-windows-shell-quotes/connecting/onprem-to-onprem/#connect-the-source-and-destination-clusters-with-mongosync)
- [Connect a Self-Managed Cluster to …
=> DOCS-16353 Double Quotes for mongosync Connection Strings

source/includes/opts/loadlevel-warning.rst, source/reference/configuration.txt, source/reference/mongosync.txt
Add warning for loadLevel setting
https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-32921/reference/mongosync/#std-option-mongosync.--loadLevel
https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-32921/reference/configuration/#mongodb-setting-loadLevel
https://jira.mongodb.org/browse/DOCSP-32921
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6500baf224fcc731b4809d7f
=> DOCSP 32921 Add warning for --loadLevel setting

snooty.toml, source/reference/api/start.txt, source/reference/collection-level-filtering.txt, source/reference/collection-level-filtering/filter-regex.txt, source/reference/limitations.txt, source/reference/versioning.txt, source/release-notes.txt, source/release-notes/1.6.txt
Restores 1.6 release content that was previously removed.  Adds new bug fixes to release notes.
* [start](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-33176-restore-1.6/reference/api/start/#request-body-parameters), restores``excludeNamespaces`
* [Filtered Sync](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-33176-restore-1.6/reference/collection-level-filtering/), restores intro and restores the FIlter Syntax section and `excludeNamespaces` back into the example
* Restores [Regex in Filters](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-33176-restore-1.6/reference/collection-level-filtering/filter-regex/)
* [RN](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-33176-restore-1.6/release-notes/1.6/)
* …
=> DOCSP-33176 restore 1.6 Content

source/release-notes/1.6.txt
Removes duplicate release note from the 1.6 RN page.
* [Staging](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-33352-dupliate-rn/release-notes/1.6/)
* [DOCSP-33352](https://jira.mongodb.org/browse/DOCSP-33352)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6515ab10492df295cfb26635)
=> DOCSP-33352 Removes duplicate release note entry from 1.6

source/reference/limitations.txt
adding mongosync limitation about consistent index specifications
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-30395/reference/limitations/#sharded-clusters
https://jira.mongodb.org/browse/DOCSP-30395
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=651f15a8885de6b26bd335a4
=> Docsp 30395 adding index consistency limitations 

source/reference/api/reverse.txt
Documents how to validate collections to ensure that unique indexes are correctly formatted.
* [Validate Unique Indexes](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-32087-reverse-req/reference/api/reverse/#validate-unique-indexes)
* [DOCSP-32087](https://jira.mongodb.org/browse/DOCSP-32087)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64dbadda67dbe91010e005f9)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e4ed0b57e37806c546d247)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6532e5673ede3ec111b1bb13)
=> DOCSP-32087 reverse req

source/includes/collections/behavior-capped-collections.rst, source/reference/api/start.txt, source/reference/limitations.txt
Updating bullets for mongosync bullets
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-33890/reference/limitations/
https://jira.mongodb.org/browse/DOCSP-33890
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65491080bd8a7a95794e1687
=> DOCSP 33890 updating mongosync limitations bullets

source/includes/collections/behavior-capped-collections.rst, source/reference/api/start.txt, source/reference/limitations.txt
Ports [#178](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/178) to v1.7 
[Build log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654a81de5b686d6bd916c12f)
=> DOCSP 33890 updating mongosync limitations bullets (#178)

source/includes/fact-write-blocking-enable.rst, source/reference/mongosync.txt
Clarifying when writes are blocked with mongosync 
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCS-16422/reference/mongosync/#write-blocking
https://jira.mongodb.org/browse/DOCS-16422
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654becfe5b686d6bd97d3f7f
=> DOCS-16422 clarifying write blocking behavior

source/reference/api/reverse.txt
Clarify mongosync reverse documentation unique index limitation with steps on resending all nodes in a source cluster. 
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-31207/reference/api/reverse/#validate-unique-indexes
https://jira.mongodb.org/browse/DOCSP-31207
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654bdb2d5b686d6bd975ac96
=> DOCSP 31207 Clarify mongosync reverse documentation unique index limitation

source/includes/api/requests/start-filtered.sh, source/reference/collection-level-filtering.txt, source/reference/collection-level-filtering/filter-regex.txt, source/release-notes/1.6.txt
Fixes all instances where `collectionsRegex` was incorrectly documented. 
Correct syntax in `mongosync` repo found here: https://github.com/search?q=repo%3A10gen%2Fmongosync+collectionsRegex&type=code
- [Regex in Filters page](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-34081-regex-filters-typo/reference/collection-level-filtering/filter-regex/#syntax)
- [Filter syntax](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-34081-regex-filters-typo/reference/collection-level-filtering/#filter-syntax)
- [1.6 release notes](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-34081-regex-filters-typo/release-notes/1.6/#regular-expression-filters)
https://jira.mongodb.org/browse/DOCSP-34081
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName …
=> DOCSP-34081 collectionsRegex typos

source/reference/mongosync.txt
- clarifies that write blocking behavior is contingent on write blocking being enabled 
- notes that commit operations should take less than a few mins per recommendation 
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-30831-mongosync-commit-operations/reference/mongosync/#commit
https://jira.mongodb.org/browse/DOCSP-30831
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6553bd095b686d6bd945257f
=> DOCSP-30831 mongosync Commit Behavior Clarification

source/multiple-mongosyncs.txt
- Remove “Stop the balancer on the Destination” step
- Remove mention of restarting balancer 
- Fix `mongosync` typos 
- Remove sentence on instances not aggregating process information 
- Add information on checking commit/sync progress
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-33886-remove-stop-balancer-on-destination/multiple-mongosyncs/
https://jira.mongodb.org/browse/DOCSP-33886
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6553e02a5b686d6bd95518b3
=> DOCSP-33886 Remove 'Stop Balancer on Destination' Step

source/includes/cross-version-sync.rst, source/includes/fact-minimum-fcv.rst, source/includes/fact-minimum-server-version-support.rst, source/quickstart.txt, source/reference/limitations.txt, source/reference/versioning.txt
- Moved versioning information from Limitations section to Server Version Compatibility and Support section
- Replace server version compatibility table with information from above bullet
- Modified limitations bullet to remove mention of minimum supported server version
- Removed limitation bullet on source and destination clusters allowing different patch releases
- Removed limitation bullet on requiring same fCV
- Fixed typo on Server Version Compatibility and Support list item 
- Added reference to server compatibility section in quickstart#179 
- [Quickstart](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-33885-server-version-rec-references/quickstart/#define-a-source-and-a-destination-cluster)
- [Limitations](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DO …
=> DOCSP-33885 Fix Server Version Requirement References

source/reference/mongosync.txt
- adding info on default read and write concern settings for mongosync
- reorganized write blocking section that was incorrectly split up
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-38407/reference/mongosync/#read-and-write-concern
https://jira.mongodb.org/browse/DOCSP-28407
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6565137a13dc9d16ea96c4e0
=> DOCSP38407  read and write concern info for mongosync

source/faq.txt, source/includes/fact-minimum-fcv.rst
- Fixed 404 link that references fCV page on server docs
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-34646-fcv-404/reference/versioning/#mongodb-server-version-compatibility-and-support:~:text=6.1%20or%206.2.-,The%20minimum%20supported%20server,is%206.0.,-Synchronize%20Data%20Between
https://jira.mongodb.org/browse/DOCSP-34646
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=656611ee13dc9d16ead2d49b
=> DOCSP-34646 Fix 404 fCV Link

source/multiple-mongosyncs.txt
clarify that the number of mongosync instances must match the number of shards 
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-33786/multiple-mongosyncs/
https://jira.mongodb.org/browse/DOCSP-33786
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6567afc37a5cb5fef5533820
=> DOCSP-33786 clarify number of mongosync instances

source/quickstart.txt
adding info on one time sync and continuous replication on the C2C quickstart page
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-33761/quickstart/#synchronize-data-between-clusters
https://jira.mongodb.org/browse/DOCSP-33761
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=656758f27a5cb5fef530c914
=> DOCSP 33761 - adding to C2C quickstart

source/installation/install-on-macos.txt
Changes extract instructions from tar to unzip.
* [Unzip Archive](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-34742-unzip-mac/installation/install-on-macos/#unzip-the-files-from-the-downloaded-archive.)
* [DOCSP-35742](https://jira.mongodb.org/browse/DOCSP-34742)
* [2023-12-12](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6578e38c7a5cb5fef580f91d)
=> DOCSP-35742 Fixes Mac Extraction

source/release-notes/1.2.txt
Clarifying that pre 6.0 release sync is only supported for one time migrations in the 1.2 release notes
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-28526/release-notes/1.2/#migrating-older-versions-of-mongodb
https://jira.mongodb.org/browse/DOCSP-28526
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6578b44e7a5cb5fef56fe0ef
=> DOCSP-28526 1.2 release notes clarification

source/reference/mongosync.txt
removing duplicate commit, user permissions, permissible reads, and permissible writes sections
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-35053/reference/mongosync/
https://jira.mongodb.org/browse/DOCSP-35053
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657b61747a5cb5fef5397ed4
=> DOCSP-35053 removing duplicate sections

source/connecting/atlas-to-atlas.txt, source/connecting/onprem-to-atlas.txt, source/includes/fact-atlas-require-indexes-limitation.rst, source/reference/limitations.txt
Adds a note to C2C docs about disabling the **Require Indexes for All Queries** option on Atlas before running `mongosync`
- [Limitations](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-33161-disable-require-indexes-option/reference/limitations/#:~:text=Before%20you%20attempt%20to%20run%20mongosync%20with%20an%20M10%2B%20Atlas%20cluster%2C%20disable%20the%20Require%20Indexes%20for%20All%20Queries%20option.)
- [Connect Two Atlas Clusters](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-33161-disable-require-indexes-option/connecting/atlas-to-atlas/#limitations)
- [Connect a Self-Managed Cluster to Atlas](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-33161-disable-require-indexes-option/connecting/onprem-to-atlas/#limitations) …
=> DOCSP-33161 Disable Require Indexes Option on Atlas

source/multiple-mongosyncs.txt
clarifying that the same version of mongosync must be used between all instances
https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-24715/multiple-mongosyncs/#configure-multiple-mongosync-instances
https://jira.mongodb.org/browse/DOCSP-24715
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65831e407a5cb5fef5098dc8
=> DOCSP 24715 mongosyncs must be the same version

source/multiple-mongosyncs.txt
Ports #231 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65983f10dcc0144a516db264)
=> DOCSP 24715 mongosyncs must be the same version (#231)

source/reference/mongosync.txt
adding sorting and uuids information to mongosync page
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-29155/reference/mongosync/#uuids
https://jira.mongodb.org/browse/DOCSP-29155
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6580ab867a5cb5fef55f4e19
=> DOCSP 29155 adding sort and uuids to mongosync page

source/reference/api/commit.txt, source/reference/disaster-recovery.txt
adding information to the commit page to clarify behavior
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-28174/reference/api/commit/
https://jira.mongodb.org/browse/DOCSP-28174
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6579e76f7a5cb5fef5c7c6c4
=> DOCSP 28174 adding info to commit page

source/faq.txt
Adds an FAQ entry for TTL indexes in mongosync.
* [FAQ Entry](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-33581-ttl-index/faq/#does-mongosync-support-ttl-indexes-)
[DOCSP-33581](https://jira.mongodb.org/browse/DOCSP-33581)
* [2023-11-1 3p](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6542b327bd8a7a9579fe33cd)
* [2024-01-10](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=659f2200dcc0144a511020a3)
=> DOCSP-33581 TTL Index Support

source/quickstart.txt
Adds the `--logPath` option to the Quickstart page to better emphasize use of logs for customers.
[Quickstart](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-31136-logPath-quickstart/quickstart/#initialize-mongosync)
* [DOCSP-31136](https://jira.mongodb.org/browse/DOCSP-31136)
* [2023-12-14](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657b712b7a5cb5fef53e4608)
* [2024-01-10](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=659edd59dcc0144a51f3ade2)
* [2024-01-11](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a07800dcc0144a5171ebe8)
=> DOCSP-31136 Adds --logPath to Quickstart

source/includes/api/tables/progress-response.rst
Adds notes on `progress` output to note where field is global or per-mongosync.
[Output](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-33577-progress-updates/reference/api/progress/#successful-response)
[DOCSP-33577](https://jira.mongodb.org/browse/DOCSP-33577)
* [2023-11-1 4p](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6542c4e6bd8a7a9579038a5a)
* [2024-01-10](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=659f231adcc0144a51107de7)
* [2024-01-11](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a075f2dcc0144a5171345f)
=> DOCSP-33577 progress output clarification

source/reference/api/start.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b2931384f878f2a7261097)
=> DOCSP-29172 Fixes buildIndexes Data Type (#242)

source/includes/api/tables/progress-response.rst
Adds note to `lagTimeSeconds` indicating that it doesn't hit 0.
[progress Response](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-27579-lagTimeSeconds/reference/api/progress/#successful-response)
[DOCSP-27579](https://jira.mongodb.org/browse/DOCSP-27579)
* [2024-01-26 1](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b3e89a94771f7657ec592f)
* [2024-01-26 2](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b425b194771f76570628e0)
* [2024-01-29](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b81cd46b2f17c95a94c0c2)
=> DOCSP-27579 lagTimeSecond fix

source/reference/limitations.txt
Adds sync limitation: mongosync does not sync users and roles.
* [General Limitations](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-33399-role-limitation/reference/limitations/#general-limitations) (last entry)
[DOCSP-33399](https://jira.mongodb.org/browse/DOCSP-33399)
* [2024-01-26](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b4300994771f76570acc82)
=> DOCSP-33399 role limitation

source/includes/table-permissions-self-hosted.rst
Reworks the table of roles required for self-managed clusters to include `dbAdmin` on destination cluster for reversing sync.  Also updates the listed roles to render as links.
[Table](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-34408-req-roles/reference/permissions/#self-managed-clusters)
* [DOCSP-34408](https://jira.mongodb.org/browse/DOCSP-34408)
* [2024-01-29](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b82aa86b2f17c95a9abe96)
* [2024-01-31](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ba7beb6b2f17c95a52292b)
* [2024-02-01](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65bbf0636b2f17c95acc1ec6)
* [2024-02-02](https://workerpool-boxgs.mongodbstitch.com/pages/jo …
=> DOCSP-34408 Updates Role Requirements

source/reference/api/start.txt
Add note to the `/start` endpoint indicating that `enableUserWriteBlocking` must be set to `true` when reversing sync.
[start](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-23551-reversible-req/reference/api/start/#request-body-parameters)
[DOCSP-23551](https://jira.mongodb.org/browse/DOCSP-23551)
* [2024-01-26 1](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b428a594771f7657071a89)
* [2024-02-05](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c14bb96b2f17c95a177957)
=> DOCSP-23551 Adds reversible note

source/quickstart.txt, source/reference/limitations.txt
Clarifies source and destination clusters on the Quickstart page.
[Setup](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-16529-src-dest-type/quickstart/#setup)
[DOCS-16529](https://jira.mongodb.org/browse/DOCS-16529)
* [2024-01-10](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=659edb2edcc0144a51f2dd18)
* [2024-01-12](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a17e55dcc0144a51ba48d8)
* [2024-01-16](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a6e76ddcc0144a51048efb)
* [2024-02-08](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c53a716b2f17c95a461471)
=> DOCSP-16529 Clarifies source/destination clusters on Quickstart

source/includes/api/tables/progress-response.rst
Clarifies that `estimatedTotalBytes` and `estimatedCopiedBytes` refer to the initial collection copy.
* [/progress Response](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-24946-collectionCopy/reference/api/progress/#successful-response)
[DOCSP-24946](https://jira.mongodb.org/browse/DOCSP-24946)
* [2024-02-01](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65bc22406b2f17c95ae23547)
* [2024-02-12](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ca94c1cbcd269fa5879ec3)
=> DOCSP-24946 Clarifies estimatedTotalBytes and estimatedCopiedBytes

source/reference/mongosync-states.txt
Adds `/reverse` endpoint to the `COMMITTED` state.
[States](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-25143-reversible-state/reference/mongosync-states/#state-descriptions)
* [DOCSP-25143](https://jira.mongodb.org/browse/DOCSP-25143)
* [2024-02-08](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c552986b2f17c95a510bd2)
* [2024-02-13](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65cbe086cbcd269fa5e4481b)
=> DOCSP-25143 Adds /reverse to COMMITTED state

source/includes/api/tables/progress-response.rst, source/reference/api/progress.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-36175)
- [Stage](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-36175/reference/api/progress/#successful-response)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c664c76b2f17c95a97c02e)
=> DOCSP-36175 Clarify mongosync's lagTimeSeconds field

source/includes/api/facts/multiple-mongosync-endpoints.rst, source/multiple-mongosyncs.txt, source/reference/api/commit.txt, source/reference/api/pause.txt, source/reference/api/resume.txt, source/reference/api/reverse.txt, source/reference/api/start.txt
In a multiple mongosync setup, indentical API commands must be sent to each mongosync
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-32690/multiple-mongosyncs/#configure-multiple-mongosync-instances
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-32690/reference/api/start/
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-32690/reference/api/pause/
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-32690/reference/api/resume/
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-32690/reference/api/commit/
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-32690/reference/api/reverse/
https://jira.mongodb.org/browse/DOCSP-32690
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65 …
=> DOCSP-32690 multiple mongosync endpoint note

source/includes/api/tables/progress-response.rst
clarifying that estimatedCopiedByes and estimatedTotalBytes are approximated before migration and should not be used as an indicator of progress. 
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-30174/reference/api/progress/#successful-response
https://jira.mongodb.org/browse/DOCSP-30174
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d7783e7111165982411eb5
=> DOCSP 30174 clarifying estimatedCopiedByes and estimatedTotalBytes

source/quickstart.txt
Reformatting quickstart "initialize mongosync" and "connect your clusters" sections
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-23924/quickstart/#connect-your-clusters
https://jira.mongodb.org/browse/DOCSP-23924
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65df873b11db7b0427e3bd2c
=> DOCSP-23924 reformatting quickstart

source/connecting/atlas-to-atlas.txt, source/connecting/onprem-to-atlas.txt, source/includes/example-connect-atlas.rst, source/includes/example-connect-onprem-atlas.rst
- Moved on-prem to Atlas cluster example to separate include since there are differences when connecting to Atlas
- Updated `cluster1` hosts and ports to better resemble an Atlas cluster 
- Changed connection strings to use SRV format 
- Moved note on Atlas string requirements (SRV or tls option) higher up for better visibility
- [On Prem to Atlas](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-23343-connect-self-managed-cluster-atlas/connecting/onprem-to-atlas/#example)
- [Atlas to Atlas](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-23343-connect-self-managed-cluster-atlas/connecting/atlas-to-atlas/#example)
https://jira.mongodb.org/browse/DOCSP-23343
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65de2a577111165982ce24e8
=> DOCSP-23343 Improve Atlas Connection String Example

snooty.toml, source/reference/versioning.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e22cef11db7b0427a2e79e)
=> DOCSP-32186 Version Information (#273) - Backport to v1.7

source/includes/fact-applyOps.rst, source/includes/fact-oplog-background.rst, source/reference/limitations.txt, source/reference/oplog-sizing.txt
Ports #274 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e6475011db7b0427773fcf)
=> DOCS-15446 applyOps limitation (#274)

source/connecting/atlas-to-atlas.txt, source/connecting/onprem-to-atlas.txt, source/includes/example-connect-atlas-to-atlas.rst, source/includes/example-connect-onprem-to-atlas.rst, source/includes/fact-connection-strings-atlas.rst, source/includes/fact-connection-strings-onprem.rst
- [JIRA](https://jira.mongodb.org/browse/DOCS-15748)
- Stage: 
- [Atlas to Atlas](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCS-15748/connecting/atlas-to-atlas/) 
- [Self-Managed to Atlas](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCS-15748/connecting/onprem-to-atlas/)
- [Self-Managed to Self-Managed](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCS-15748/connecting/onprem-to-onprem/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e8a2f311db7b04271bcd1f) (clean)
Tested and updated doc for Atlas connection string fix. This required fixes in multiple pages.
```
{8:12}~/server-bug-bash ➭ mongosync \
--logPath data/log/mongosync \
--cluster0 …
```
=> DOCS-15748 Fix Mongosync Atlas doc examples

source/reference/limitations.txt, source/reference/mongosync.txt
correcting/adding to the mongosync multiple clusters limitations
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-34589/reference/limitations/#multiple-clusters
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-34589/reference/mongosync/#multiple-clusters
https://jira.mongodb.org/browse/DOCSP-34589
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65de1fb17111165982c9ea2a
=> DOCSP-34589 clarify multiple mongosync limitations

source/reference/api/reverse.txt
Adds requirement to `reverse` that the destination cluster cannot rollover before `mongosync` reaches the `COMMITTED` state.
[reverse Requirement](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-37408-oplog-rollover/reference/api/reverse/#requirements)
[DOCSP-37408](https://jira.mongodb.org/browse/DOCSP-37408)
* [2024-03-06](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e8da9211db7b04273beeff)
* [2024-03-08](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65eb5f936fc5f04850b01a14)
=> DOCSP-37408 Rollover Requirement

source/reference/limitations.txt, source/reference/mongosync.txt
Ports #271 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ef1aab6fc5f04850621770)
=> DOCSP-34589 clarify multiple mongosync limitations (#271)

source/reference/mongosync-states.txt
Adds `REVERSING` to table of mongosync states.
* [mongosync States](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCS-16652-mongosync-states/reference/mongosync-states/#state-descriptions)
[DOCS-16652](https://jira.mongodb.org/browse/DOCS-16652)
* [2024-03-05](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e75b5311db7b0427bebccd)
* [2024-03-13](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f1ceee6fc5f048501f7b86)
=> DOCS-16652 Adds Reversing State

source/installation/install-on-linux.txt, source/installation/install-on-macos.txt, source/quickstart.txt
_Primary fix_: Updates installation procedure for Mac OS.
_Secondary fix_: This PR removes the **Run Cluster-to-Cluster Sync** sections of the install pages. 
Ratika points out that the page linked to in the **Run Cluster-to-Cluster Sync** sections of both the Linux and Mac OS install pages is a placeholder page. See screenshot below. (Note that "**Cluster-to-Cluster Sync ->**" points to the homepage and is auto-generated footer content.)
These sections can later be reinstated when the placeholder page is populated with content.
- https://preview-mongodbjmdmongo.gatsbyjs.io/cluster-sync/DOCSP-34744/installation/install-on-macos/
- https://preview-mongodbjmdmongo.gatsbyjs.io/cluster-sync/DOCSP-34744/installation/install-on-linux/
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?col …
=> DOCSP-34744 fixes c2c installation procedure

source/reference/disaster-recovery.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-24392)
- [Stage](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-24392/reference/disaster-recovery/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65fc743d6fc5f04850b67ac1) (contains errors not introduced by changes in this PR)
=> DOCSP-24392 Add index constraint command examples to mongosync

source/includes/fact-api-endpoint.rst, source/reference/api/commit.txt, source/reference/api/pause.txt, source/reference/api/progress.txt, source/reference/api/resume.txt, source/reference/api/reverse.txt, source/reference/api/start.txt
Adds a notice to each mongosync API endpoint indicating that mongosync does not protect the endpoint, but notes that by default it is bound to localhost only and that it doesn't expose connection details or user data.
Note added to the descriptions of these pages:
* [start](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-32282-api-security/reference/api/start/)
* [progress](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-32282-api-security/reference/api/progress/)
* [pause](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-32282-api-security/reference/api/pause/)
* [resume](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-32282-api-security/re …
=> DOCSP-32282 API Security

source/reference/mongosync.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-29181)
- [Stage](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-29181/reference/mongosync/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6604548a6fc5f048507d67d1)
=> DOCSP-29181 mongosync documentation update

source/includes/fact-oplog-background.rst, source/includes/read-preference-connection-string.rst, source/multiple-mongosyncs.txt, source/reference/limitations.txt, source/reference/mongosync.txt, source/release-notes/1.7.txt, source/using-mongosync.txt
Adds release notes for v1.7.2.
* [RN](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-35932-1.7.2-RN/release-notes/1.7/#1.7.2-release)
* [General Limitations](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-35932-1.7.2-RN/reference/limitations/#general-limitations) (last bullet)
* [Sharded Limitations](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-35932-1.7.2-RN/reference/limitations/#sharded-clusters) (last two bullets)
* [Sharded Sync](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-35932-1.7.2-RN/multiple-mongosyncs/) (important admonition at top of page).
* [Read Preference](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-35932-1.7.2-RN/reference/mongosync/#read-preference)
* [oplog …
=> DOCSP-36932 RN for 1.7.2

source/includes/fact-oplog-background.rst, source/includes/read-preference-connection-string.rst, source/multiple-mongosyncs.txt, source/reference/limitations.txt, source/reference/mongosync.txt, source/release-notes/1.7.txt, source/using-mongosync.txt
Ports #265 to v1.7
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660ec1a53a5920a2910a236a)
=> DOCSP-36932 RN for 1.7.2 (#265)

source/reference.txt, source/reference/cutover-process.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-38149)
- [Stage](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-38149/reference/cutover-process)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660ef6383a5920a29126f384)
=> DOCSP-38149 Add documentation for mongosync cutover processs

source/includes/api/responses/progress.json, source/includes/api/tables/progress-error-response.rst, source/includes/api/tables/progress-response.rst, source/reference/api/progress.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-34591)
- [Stage](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-34591/reference/api/progress/#error-response)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660dbe2a3a5920a291c9aa74)
=> DOCSP-34591 Add errorDescription and success keys to progress response

source/reference/api/start.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-23937): Document for [setUserWriteBlockMode](https://www.mongodb.com/docs/master/reference/privilege-actions/#mongodb-authaction-setUserWriteBlockMode) and [bypassWriteBlockingMode](https://www.mongodb.com/docs/master/reference/privilege-actions/#mongodb-authaction-bypassWriteBlockingMode) specify that these roles should be applied to the cluster resource, but current example in [doc](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/api/start/#user-write-blocking) shows these applied on the db/collection. Fixes incorrect documentation.
- [Stage](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-23937/reference/api/start/#user-write-blocking/) 
- …
=> DOCSP-23937 Fix Role Issue on Mongosync Start Page

source/index.txt, source/quickstart.txt
Standardize quickstart page names. Add product name for C2C quickstart page.
https://preview-mongodbjeffallenmongo.gatsbyjs.io/cluster-sync/DOCSP-38546/quickstart/
https://jira.mongodb.org/browse/DOCSP-38546
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661fddeb3a5920a29101c065
=> (DOCSP-38546): Add product name to quickstart page

source/includes/fact-write-blocking-enable.rst, source/reference/api/commit.txt, source/reference/disaster-recovery.txt
Adds note on read-only behavior of source cluster when write blocking is enabled and `commit` is received. 
Note that I swapped out the description with an abbreviated version of the include text since not all the information from the original include is relevant to the table information. 
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-38839-source-read-only-support/reference/api/commit/#description
https://jira.mongodb.org/browse/DOCSP-38839
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6622d787b67dbf804a81115c
^ warning unrelated to this PR
=> DOCSP-38839 Source Cluster Read Only Behavior

source/connecting/onprem-to-atlas.txt, source/connecting/onprem-to-onprem.txt, source/includes/migration-upgrade-recommendation.rst, source/release-notes/1.7.txt
Recommend that users upgrade to the latest server patch prior to migration
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-39091/release-notes/1.7/#minimum-supported-version
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-39091/connecting/onprem-to-onprem/
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-39091/connecting/onprem-to-atlas/
https://jira.mongodb.org/browse/DOCSP-39091
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66312de3b67dbf804aa92668
[What's expected of an external …
=> DOCSP-39091  Recommend that users upgrade to the latest server patch

source/reference/limitations.txt
Add limitation that mongosync does not support syncing atlas search indexes
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-39095/reference/limitations/#general-limitations
https://jira.mongodb.org/browse/DOCSP-39095
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66325c40b67dbf804af25dfc
=> DOCSP-39095 adding atlas search indexes limitation

source/reference/mongosync.txt
Recommend limiting DDL operations during a sync
https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-39098/reference/mongosync/#data-definition-language--ddl--operations
https://jira.mongodb.org/browse/DOCSP-39098
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66324f30b67dbf804aec9d92
=> DOCSP 39098  Recommend limiting DDL operations during a sync

source/includes/limitations-filtering.rst
Clarifies view sync.
[Limtations](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-39594-view-clarification/reference/collection-level-filtering/#limitations) sixth bullet.
[DOCSP-39594](https://jira.mongodb.org/browse/DOCSP-39594)
* [2024-05-21](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664d1313cf5bec1c29808574)
* [2024-05-22](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664e30a2cf5bec1c29c1f6f1)
=> DOCSP-39594 View Clarification

source/reference/api/reverse.txt
Updates the `/reverse` endpoint to indicate that writes included in the reversal begin at `canWrite=true`.
* [Description](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-39211-reverse/reference/api/reverse/#description) last line.
* [Requirements](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-39211-reverse/reference/api/reverse/#requirements) third bullet.
[DOCSP-39211](https://jira.mongodb.org/browse/DOCSP-39211)
* [2024-04-21](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664cde56cf5bec1c2970f8b6)
* [2024-04-22](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664e2fa1cf5bec1c29c1a78e)
* [2024-04-22a](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664e3628 …
=> DOCSP-39211 reverse update

source/includes/limitations-filtering.rst
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664e35c2cf5bec1c29c34e63)
=> DOCSP-39594 View Clarification (#321)

source/includes/document-filtering-intro.rst, source/includes/orr-intro.rst, source/reference/beta-program.txt, source/reference/beta-program/orr.txt, source/release-notes/1.8.txt
- Creates reference page for ORR 
- Adds note on ORR to 1.8 beta release notes 
- Adds ORR to beta program feature table
- [Beta Feature table](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-38286-enable-ORR/reference/beta-program/#beta-features)
- [ORR reference page](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-38286-enable-ORR/reference/beta-program/orr/#std-label-c2c-beta-orr)
- [1.8 RN](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-38286-enable-ORR/release-notes/1.8/#oplog-rollover-resilience)
https://jira.mongodb.org/browse/DOCSP-38286
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66846c07fe162e5006346204
=> DOCSP-38286 Enable ORR

source/quickstart.txt, source/reference/cutover-process.txt
added code snippets for steps 1, 2, 3, 4, and 7 to the "Finalize Cutover Process" page. Also added reference to page on quickstart page
https://preview-mongodbsonderdonkmdb.gatsbyjs.io/cluster-sync/DOCSP-41102/quickstart/#finalize-cutover-process
https://preview-mongodbsonderdonkmdb.gatsbyjs.io/cluster-sync/DOCSP-41102/reference/cutover-process/ 
https://jira.mongodb.org/browse/DOCSP-41102
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=668c4f36fb8bd13b8437bd8b
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+Mo …
=> DOCS-41102 added code snippets cutover page

source/faq.txt, source/includes/fact-restart-resume-delay.rst, source/reference/api/progress.txt, source/reference/api/resume.txt, source/reference/mongosync-states.txt, source/release-notes.txt, source/release-notes/1.7.txt
- Documents 2-minute delay behavior when resuming/restarting sync operations. 
- added 1.8 release notes to toc to fix build error
- [/progress](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-40138-Mongosync-Delay-After-Resume-Restart/reference/api/progress/#behavior)
- [/resume](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-40138-Mongosync-Delay-After-Resume-Restart/reference/api/resume/#behavior)
- [mongosync states](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-40138-Mongosync-Delay-After-Resume-Restart/reference/mongosync-states/#view-the-current-state)
- [FAQ](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-40138-Mongosync-Delay-After-Resume-Restart/faq/#can-i-configure-mongosync-for-high-availability-) - this section …
=> DOCSP-40138-Mongosync-Delay-After-Resume-Restart

source/reference/api/progress.txt
Quick typo bug fix in 1.7 only.
Build log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66969f0626eba795526eea12
Staging: https://preview-mongodbmdbashley.gatsbyjs.io/cluster-sync/DOCSP-40979-typo-fix/reference/api/progress/#response
=> DOCSP-40979: fix typo in /progress 

source/reference/limitations.txt
Adds note on ``mongosync`` only supporting clusters that use WiredTiger
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-40105-storageEngine-limitation/reference/limitations/#:~:text=mongosync%20only%20supports%20clusters%20that%20use%20the%20WiredTiger%20storage%20engine
https://jira.mongodb.org/browse/DOCSP-40105
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6697d5a026eba79552b75cb2
=> DOCSP-40105-storageEngine-limitation

source/reference/api/reverse.txt
Added a description of the REVERSING state on the /reverse API endpoint page.
Note for reviewers: This ticket also entailed adding the REVERSING state to the mongosync States page. This was actually already done and just not backported. The change has been backported now. You can see that change here: #282 
https://preview-mongodbsonderdonkmdb.gatsbyjs.io/cluster-sync/DOCSP-41445/reference/api/reverse/#behavior
https://jira.mongodb.org/browse/DOCSP-41445
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=669fe7cb26eba795527bae0e
[What's expected of an external …
=> DOCSP-41445 added reversing state in docs

source/release-notes/1.8.txt
Adds release notes for mongosync 1.8.0
https://preview-mongodbjwilsonmdb.gatsbyjs.io/cluster-sync/DOCSP-41580/release-notes/1.8/
https://jira.mongodb.org/browse/DOCSP-41580
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66a3effb26eba7955279cb9d
=> DOCSP-41580 creates release notes for 1.8.0

source/includes/api/tables/progress-response.rst, source/reference/api/progress.txt, source/reference/api/start.txt, source/reference/telemetry.txt
Makes requested documentation changes to support the release of `mongosync` 1.8.0
Note to reviewers: The writing was internally reviewed in #352. This PR moves the writing out of release notes and into the documentation. 
https://jira.mongodb.org/browse/DOCSP-41853
[/start](https://preview-mongodbjwilsonmdb.gatsbyjs.io/cluster-sync/DOCSP-41853/reference/api/start/#required-indexes)
[/progress - totalEventsApplied added to response](https://preview-mongodbjwilsonmdb.gatsbyjs.io/cluster-sync/DOCSP-41853/reference/api/progress/#successful-response)
[/progress - adds new behaviors to Behavior section](https://preview-mongodbjwilsonmdb.gatsbyjs.io/cluster-sync/DOCSP-41853/reference/api/progress/#behavior)
[telemetry - moves "Hostnames" from untracked to …
=> DOCSP-41853 Updates mongosync documentation to support 1.8 release

source/includes/api/requests/start-namespace-remap.sh, source/includes/fact-valid-namespace-remap.rst, source/reference/api/start.txt, source/reference/beta-program/namespace-remapping.txt, source/release-notes/1.8.txt
Documents namespace remapping for beta program.
* [namespaceRemap](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-39059-namespace-remap/reference/api/start/#request-body-parameters) parameters
* [Example](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-39059-namespace-remap/reference/api/start/#example--start-sync-to-remap-namespaces)
* [Change Collection Namespace](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-39059-namespace-remap/reference/beta-program/namespace-remapping/)
* [RN](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-39059-namespace-remap/release-notes/1.8/#namespace-remapping)
* [Valid Namespace Remapping](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-39059-namespace-remap/referenc …
=> DOCSP-39059 namespace remap

source/release-notes/1.7.txt
- Fixes typo regarding bug introduced in 1.7.0
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-41855-1.7.3-bug/release-notes/1.7/#1.7.3-release
https://jira.mongodb.org/browse/DOCSP-41855
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66ad3a32824f175afd2335f5
=> DOCSP-41855-1.7.3-bug-typo

source/includes/fact-valid-namespace-remap.rst, source/index.txt, source/release-notes/1.8.txt
- Add limitation to namespace remapping 
- Remove in-dev.rst banners
- [mongosync Landing page (removed in-dev banner)](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-42176-c2c-1.8-fast-follow/)
- [1.8 release notes (removed in-dev banner)](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-42176-c2c-1.8-fast-follow/release-notes/1.8/)
- [Namespace Remapping limitation](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-42176-c2c-1.8-fast-follow/reference/beta-program/namespace-remapping/#std-label-c2c-beta-namespace-remapping:~:text=You%20can%27t%20specify%20a%20namespace%20remap%20and%20set%20the%20reversible%20flag%20to%20true.)
https://jira.mongodb.org/browse/DOCSP-42176
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&job …
=> DOCSP-42176-c2c-1.8-fast-follow

config/redirects, snooty.toml, source/reference/beta-program.txt, source/release-notes/1.8.txt
- Update redirects file to include 1.8 in `versions` variable.
- Update snooty.toml version constants for version
- Edited constants used to refer to beta program in 1.8 docs
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-42292-update-version-flipper/reference/beta-program/
https://jira.mongodb.org/browse/DOCSP-42292
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66b4e57a824f175afdc93be3
=> DOCSP-42292-update-redirects-config

source/reference/limitations.txt
- Add timestamp limitation 
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-37061-mongosync-timestamp-limitation/reference/limitations/#general-limitations
https://jira.mongodb.org/browse/DOCSP-37061
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66ba647a83839571177a6a44
=> DOCSP-37061-mongosync-timestamp-limitation

source/release-notes/1.8.txt
- Add into 1.8 release notes that `mongosync` now errors if a sync restarts with different source/destination clusters
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-36050-mongosync-diff-source-error/release-notes/1.8/#other-notes:~:text=mongosync%20now%20exits%20with%20an%20error%20if%20it%20stops%20and%20restarts%20with%20a%20different%20source%20or%20destination%20cluster%20than%20previously%20specified.
https://jira.mongodb.org/browse/DOCSP-36050
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66be60dd8e811ae672391f34
=> DOCSP-36050 mongosync restarts with different source or destination 

source/reference/api/commit.txt
- Reword `commit` limitation regarding mongosync forbidding source writes until commit
- Add warning for potential data loss
https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-35777-source-writes-requirement/reference/api/commit/#requirements
https://jira.mongodb.org/browse/DOCSP-35777
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66be6f8d8e811ae6723d0d6b
=> DOCSP-35777 Source Writes After Commit

source/includes/warn-option-cluster-password-visibility.rst, source/reference/mongosync.txt
Adds a warning to the `--cluster0` and `--cluster1` options about password visibility when using these options.
https://jira.mongodb.org/browse/DOCSP-23892
[--cluster0](https://preview-mongodbjwilsonmdb.gatsbyjs.io/cluster-sync/DOCSP-23892/reference/mongosync/#std-option-mongosync.--cluster0)
[--cluster1](https://preview-mongodbjwilsonmdb.gatsbyjs.io/cluster-sync/DOCSP-23892/reference/mongosync/#std-option-mongosync.--cluster1)
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66be69b38e811ae6723b7e1a
=> DOCSP-23892 adds warning for cluster options

snooty.toml, source/includes/fact-minimum-server-version-support.rst, source/reference/beta-program/document-filtering.txt, source/reference/beta-program/namespace-remapping.txt, source/release-notes/1.7.txt
- Updates minimum supported server version for 1.8+
- Note the values will be adjusted in the 1.7 backport
- Updates minimum supported server version in 1.7.3
- [mongosync reference - compatibility](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-39103-min-server-versions/reference/mongosync/#compatibility)
- [server version compatibility](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-39103-min-server-versions/reference/supported-server-version/#mongodb-server-version-compatibility) 
- [1.8 release notes](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-39103-min-server-versions/release-notes/1.8/#minimum-supported-version)
- [1.7 release notes](https://preview-mongodbajhuhmdb.gatsbyjs.io/cluster-sync/DOCSP-39103-min-server-versions/release-not …
=> DOCSP-39103 Minimum Server Versions

source/reference/beta-program/abc-migration.txt
Adds note about sizing cluster B to handle a heavy load from A and C.
[Cluster B Size](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-42568-abc-notice/reference/beta-program/abc-migration/#cluster-size)
[DOCSP-42568](https://jira.mongodb.org/browse/DOCSP-42568)
* [2024-08-16](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bf92c18e811ae6727c5c18)
* [2024-08-16 / 1](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bfcb0c8e811ae6728fdcba)
=> DOCSP-42568 Cluster B Size for ABC Migration

source/quickstart.txt
Adds note to quickstart that the source cluster can remain active during sync.
[Quickstart](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-38635-active-source/quickstart/), last bullet.
[DOCSP-38635](https://jira.mongodb.org/browse/DOCSP-38635)
* [2024-08-22](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c784fe40f3e3c8734df2d4)
=> DOCSP-38635 sync active source cluster

source/reference/api/reverse.txt
- Adds limitation to `reverse` endpoint documentation that it isn't supported with filtered sync.
https://deploy-preview-409--docs-cluster-to-cluster-sync.netlify.app/reference/api/reverse/#limitations
https://jira.mongodb.org/browse/DOCSP-43489
=> DOCSP-43489-reverse-filtered-sync-compat

source/includes/api/tables/progress-response.rst, source/reference/api/commit.txt, source/reference/api/start.txt
Removed admonitions in tables.
https://deploy-preview-416--docs-cluster-to-cluster-sync.netlify.app/reference/api/commit/
https://deploy-preview-416--docs-cluster-to-cluster-sync.netlify.app/reference/api/progress/
https://deploy-preview-416--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/
https://jira.mongodb.org/browse/DOCSP-42974
https://app.netlify.com/sites/docs-cluster-to-cluster-sync/deploys/66e9d7caba87220008efcfe4
=> DOCSP-42974-c2c-nested-components

source/release-notes.txt
- Updated current stable release on release notes for v1.8 branch. 
- **NOTE**: removed the "upcoming stable release" section since the 1.9 release notes aren't available on the v1.8 branch. The upcoming release section is visible on the [v1.9 branch](https://www.mongodb.com/docs/cluster-to-cluster-sync/upcoming/release-notes/)
https://deploy-preview-425--docs-cluster-to-cluster-sync.netlify.app/release-notes/
https://jira.mongodb.org/browse/DOCSP-44182
=> DOCSP-44182-stable-release

source/reference/api/reverse.txt
Added a link to the write blocking page on the reverse API page.
https://deploy-preview-426--docs-cluster-to-cluster-sync.netlify.app/reference/api/reverse/
https://jira.mongodb.org/browse/DOCSP-43492
=> DOCSP-43492-blocking-link-reverse-sync

source/reference/api/reverse.txt, source/reference/beta-program.txt
Added a note explaining that mongosync reverse mode is not compatible with beta features. 
https://deploy-preview-424--docs-cluster-to-cluster-sync.netlify.app/reference/beta-program/
https://jira.mongodb.org/browse/DOCSP-43751
=> DOCSP-43751-mongosync-beta-reverse

source/release-notes/1.8.txt
=> DOCSP-43827 1.8.1 RN (#430)

source/reference/mongosync/mongosync-behavior.txt
Mongosync rewrites any legacy index key values that is 0 or an empty string from the source to a valid value (1) on the destination. This should be documented on the [mongosync behavior page](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/mongosync/mongosync-behavior).
https://deploy-preview-442--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/mongosync-behavior/#legacy-index-value-rewrites
https://jira.mongodb.org/browse/DOCSP-44006
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documenta …
=> DOCSP-44006-mongosync-behavior-converting-legacy-indexes

source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-44006-mongosync-behavior-converting-legacy-indexes (#442)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/442)
- [build log](https://app.netlify.com/sites/docs-cluster-to-cluster-sync/deploys/6717f1becfda6f00087e68d5)
=> DOCSP-44006-v1.7-backport 

source/reference/limitations.txt
- Add to sharded cluster limitations that global clusters aren't supported as a source or destination
https://deploy-preview-444--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/#sharded-clusters:~:text=mongosync%20doesn%27t%20support%20sync%20to%20or%20from%20global%20clusters
https://jira.mongodb.org/browse/DOCSP-44635
=> DOCSP-44635-global-cluster-limit

source/reference/limitations.txt
- [DOCSP-44635-global-cluster-limit (#444)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/444)
=> [v1.8] DOCSP-44635-global-cluster-limit (#444)

source/reference/verification.txt, source/reference/verification/verifier.txt
Migration Verifier has the following limitation, according to the [Migration Verifier GitHub](https://github.com/mongodb-labs/migration-verifier#limitations): 
> The verifier's iterative process can handle data changes while it is running, until you hit the writesOff endpoint. However, it cannot handle DDL commands. If the verifier receives a DDL change stream event (drop, dropDatabase, rename), the verification will fail. If an untracked DDL event (create, createIndexes, dropIndexes, modify) occurs, the verifier may miss the change.
On the page instructing users on how to [Verify using Migration Verifier](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/verification/verifier/#verify-with-migration-verifier) and the [Verify Data …
=> DOCSP-43721-migration-verifier-disclaimer

source/reference/verification.txt, source/reference/verification/verifier.txt
- [DOCSP-43721-migration-verifier-disclaimer #445](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/445)
https://deploy-preview-449--docs-cluster-to-cluster-sync.netlify.app/reference/verification/#migration-verifier
https://deploy-preview-449--docs-cluster-to-cluster-sync.netlify.app/reference/verification/verifier/
=> DOCSP-43721-v1.7-backport (#445)

source/reference/api/start.txt
- the `mongosync` docs do mention that unique indexes on the source cluster that are part of sharded collections on the destination cluster *must have* the shard key as a prefix
- but this info is only in the[ “Supporting Indexes”](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/api/start/#supporting-indexes) section!
- this can be an issue if the user is looking at the ["Sharding Parameters"](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/api/start/#sharding-parameters) table and misses this info – can cause a failure during the commit phase of `mongosync`, which can take a while to get to!
This PR adds a link to the "Supporting Indexes" section in the `createSupportingIndexes` description under the "Sharding Parameters" table to ensure …
=> DOCSP-44549-specify-supporting-index-behavior

source/reference/api/start.txt
- [DOCSP-44549-specify-supporting-index-behavior #448](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/448)
https://deploy-preview-450--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/#sharding-parameters
=> DOCSP-44549-v1.7-backport (448)

source/reference/api/start.txt
- Clarifies the number of chunks that are created when syncing to a sharded cluster. 
https://deploy-preview-452--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/#pre-split-chunks
https://jira.mongodb.org/browse/DOCSP-44700
=> DOCSP-44700-pre-split-chunks

source/reference/api/start.txt
- [DOCSP-44700-pre-split-chunks (#452)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/452)
=> [v1.7] DOCSP-44700-pre-split-chunks (#452)

source/reference/api/start.txt
- [DOCSP-44700-pre-split-chunks (#452)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/452)
=> [v1.8] DOCSP-44700-pre-split-chunks (#452)

source/includes/fact-no-8.0-support.rst, source/reference/mongosync.txt, source/reference/supported-server-version.txt
- Mention that `mongosync` doesn't support 8.0 
- Document workaround for migrating to and from 8.0 source clusters
- Document workaround for migrating from 6.0/7.0 cluster to 8.0
https://deploy-preview-451--docs-cluster-to-cluster-sync.netlify.app/reference/supported-server-version/#synchronize-data-from-a-pre-8.0-source-cluster-to-an-8.0-destination-cluster
https://jira.mongodb.org/browse/DOCSP-44678
=> DOCSP-44678-mongosync-8.0-support

source/includes/fact-no-8.0-support.rst, source/reference/mongosync.txt, source/reference/supported-server-version.txt
- [DOCSP-44678-mongosync-8.0-support (#451)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/451)
=> [v1.8] DOCSP-44678-mongosync-8.0-support (#451)

source/includes/fact-no-8.0-support.rst, source/reference/supported-server-version.txt
- Fixes syntax bug that caused the list item to be bolded. 
- Also adds ref links to the sections that instruct users on how to migrate to 8.0 clusters for clarity 
https://deploy-preview-458--docs-cluster-to-cluster-sync.netlify.app/reference/supported-server-version/
https://jira.mongodb.org/browse/DOCSP-44972
=> DOCSP-44972-syntax-bug

source/includes/fact-no-8.0-support.rst, source/reference/supported-server-version.txt
- [DOCSP-44972-syntax-bug (#458)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/458)
=> [v1.8] DOCSP-44972-syntax-bug (#458)

source/reference/limitations.txt
Adds rolling index limitation 
https://deploy-preview-457--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/#rolling-index-builds
https://jira.mongodb.org/browse/DOCSP-44876
=> DOCSP-44876-rolling-index-limitation

source/reference/limitations.txt
=> DOCSP-44876-rolling-index-limitation (#457)

source/includes/rolling-build-limitation.rst, source/reference/limitations.txt, source/reference/mongosync/mongosync-behavior.txt
Adds rolling build limitation to mongosync behavior page under continuous sync considerations
https://deploy-preview-462--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/mongosync-behavior/#rolling-index-builds
https://deploy-preview-462--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/#rolling-index-builds
https://jira.mongodb.org/browse/DOCSP-45041
=> DOCSP-45041-adding-rolling-limitation-to-behavior

source/reference/beta-program/document-filtering.txt
As of 1.8.0, an invalid document filter in the start request will no longer crash mongosync; instead, the start request will fail and the user can correct the problem and re-issue the corrected start request without needing to restart mongosync. This information is now reflected in the [document filtering page](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/beta-program/document-filtering/) of the beta program in c2c sync. 
https://deploy-preview-464--docs-cluster-to-cluster-sync.netlify.app/reference/beta-program/document-filtering/#limitations
https://jira.mongodb.org/browse/DOCSP-42724
=> DOCSP-42724-invalid-document-filter-behavior

source/faq.txt
Adds note to FAQ stating index builds on destination clusters are treated as writes
https://deploy-preview-463--docs-cluster-to-cluster-sync.netlify.app/faq/#can-i-perform-reads-or-writes-to-my-destination-cluster-while-mongosync-is-syncing-
https://jira.mongodb.org/browse/DOCSP-44977
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and this [example PR](https://github.com/10gen/cloud-docs/pull/5042/files)
=> DOCSP-44977 notes index build behavior during sync

source/faq.txt
=> DOCSP-44977 notes index build behavior during sync (#463)

source/reference/api/start.txt, source/reference/mongosync/mongosync-behavior.txt
Adds info on shared cluster behavior and moves sections to the general mongosync behavior page
https://deploy-preview-472--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/mongosync-behavior/#sharded-clusters
https://deploy-preview-472--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/#behavior
https://jira.mongodb.org/browse/DOCSP-45117
=> DOCSP-45117-sharded-cluster-behavior

source/reference/api/start.txt, source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-45117-sharded-cluster-behavior (#472)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/472)
=> DOCSP-45117-sharded-cluster-behavior-v1.8-backport (472)

source/reference/api/start.txt, source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-45117-sharded-cluster-behavior (#472)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/472)
=> DOCSP-45117-sharded-cluster-behavior-v1.7-backport (472)

source/index.txt, source/reference/limitations.txt, source/release-notes/1.9.txt
Add release notes for 1.9.0
See note on embedded verifier content.
https://deploy-preview-470--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.9/#1.9.0-release
https://jira.mongodb.org/browse/DOCSP-43570
=> DOCSP-43570-mongosync-1.9.0

source/index.txt
Adds a sentence to the t[op-level page of C2C docs](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/) that links to the new [considerations for continuous sync](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/mongosync/mongosync-behavior/#considerations-for-continuous-sync) section, in order to appropriately set user expectations around what's feasible with mongosync today.
Deletes this redundant sentence: 
>In addition to continuous data synchronization, mongosync can also facilitate a one time data migration between clusters.
https://deploy-preview-478--docs-cluster-to-cluster-sync.netlify.app/
https://jira.mongodb.org/browse/DOCSP-44974
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and …
=> DOCSP-44974-cluster-to-cluster-considerations-for-continuous-sync

source/index.txt
- [DOCSP-44974-cluster-to-cluster-considerations-for-continuous-sync](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/478)
https://deploy-preview-479--docs-cluster-to-cluster-sync.netlify.app/
=> DOCSP-44974-v1.7-backport (478)

source/index.txt
- [DOCSP-44974-cluster-to-cluster-considerations-for-continuous-sync](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/478)
https://deploy-preview-480--docs-cluster-to-cluster-sync.netlify.app/
=> DOCSP-44974-v1.8-backport (#478)

config/redirects, snooty.toml
- Updates snooty & config/redirects version variables for 1.10 (upcoming)
See [Currently Supported Versions](https://deploy-preview-483--docs-cluster-to-cluster-sync.netlify.app/reference/versioning/#currently-supported-versions) section
https://jira.mongodb.org/browse/DOCSP-45319
=> DOCSP-45319-config-redirects

source/about-mongosync.txt, source/connecting.txt, source/connecting/atlas-to-atlas.txt, source/connecting/onprem-to-atlas.txt, source/connecting/onprem-to-onprem.txt, source/index.txt, source/installation.txt, source/quickstart.txt, source/reference/versioning.txt, source/release-notes.txt, source/release-notes/1.10.txt
- Adds `in-dev` include across top-level docs pages 
- Creates 1.10 release notes page 
- Update list of upcoming, stable, and previous releases on the main "Release Notes" page
**NOTE:** The Snooty variable used in the in-dev.rst include will be updated to say 1.10 in #483. Will be holding off merge of this PR until then.
https://deploy-preview-484--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.10/
https://deploy-preview-484--docs-cluster-to-cluster-sync.netlify.app/release-notes/
https://jira.mongodb.org/browse/DOCSP-45321
=> DOCSP-45321-1.10-in-dev

source/includes/fact-mongosync-balancer.rst, source/reference/mongosync/mongosync-behavior.txt, source/topologies/multiple-mongosyncs.txt
- The first ask of the ticket regarding chunk migrations has already been addressed in #472. 
- Added `important:` note regarding stopping the balancer, not running moveChunk or moveRange during migration, and how to stop the balancer.
https://deploy-preview-490--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/mongosync-behavior/#sharded-clusters
https://jira.mongodb.org/browse/DOCSP-44360
=> DOCSP-44360-chunk-migration-balancers

source/includes/fact-mongosync-balancer.rst, source/reference/mongosync/mongosync-behavior.txt, source/topologies/multiple-mongosyncs.txt
- [DOCSP-44360-chunk-migration-balancers (#490)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/490)
=> DOCSP-44360-chunk-migration-balancers-v1.9-backport (490)

source/includes/fact-mongosync-balancer.rst, source/reference/mongosync/mongosync-behavior.txt, source/topologies/multiple-mongosyncs.txt
- [DOCSP-44360-chunk-migration-balancers (#490)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/490)
=> DOCSP-44360-chunk-migration-balancers-v1.8-backport (490)

source/faq.txt, source/includes/fact-oplog-disk-storage.rst, source/includes/fact-oplog-reduction.rst, source/quickstart.txt, source/reference/oplog-sizing.txt
- Add new FAQ entry regarding hardware requirements for destination clusters.
- Add note on destination cluster disk space requirements in the Quickstart and oplog pages.
- [FAQ](https://deploy-preview-488--docs-cluster-to-cluster-sync.netlify.app/faq/#what-hardware-specifications-should-the-destination-cluster-have-)
- [oplog Sizing Considerations section](https://deploy-preview-488--docs-cluster-to-cluster-sync.netlify.app/reference/oplog-sizing/#considerations)
- [Quickstart](https://deploy-preview-488--docs-cluster-to-cluster-sync.netlify.app/quickstart/#define-a-source-and-a-destination-cluster)
https://jira.mongodb.org/browse/DOCSP-44478
=> DOCSP-44478-hardware-specs

source/faq.txt, source/includes/fact-oplog-disk-storage.rst, source/quickstart.txt, source/reference/oplog-sizing.txt
- [DOCSP-44478-hardware-specs (#488)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/488)
=> DOCSP-44478-hardware-specs-v1.8-backport (488)

source/faq.txt, source/includes/fact-oplog-disk-storage.rst, source/quickstart.txt, source/reference/oplog-sizing.txt
- [DOCSP-44478-hardware-specs (#488)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/488)
=> DOCSP-44478-hardware-specs-v1.9-backport (488)

source/faq.txt, source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-44120-clarify-mongosync-sharding-behavior (#487)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/487)
=> DOCSP-44120-clarify-mongosync-sharding-behavior-v1.8-backport (487)

source/faq.txt, source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-44120-clarify-mongosync-sharding-behavior (#487)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/487)
=> DOCSP-44120-clarify-mongosync-sharding-behavior-v1.9-backport (487)

source/includes/cluster-shutdown-warning.rst, source/reference/cutover-process.txt, source/reference/mongosync/mongosync-behavior.txt
Adding cutover warnings 
https://deploy-preview-485--docs-cluster-to-cluster-sync.netlify.app/reference/cutover-process/
https://deploy-preview-485--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/mongosync-behavior/#considerations-for-continuous-sync
https://jira.mongodb.org/browse/DOCSP-44528
=> DOCSP-44528-cutover-failure-warnings

source/reference/beta-program/destinationDataHandling.txt
adds that ignorePreExistingNamespaces is incompatible with reverse
https://deploy-preview-500--docs-cluster-to-cluster-sync.netlify.app/reference/beta-program/destinationDataHandling/#command-option
https://jira.mongodb.org/browse/DOCSP-45060
=> DOCSP-45060-ignorePreExistingNamespaces-incompatibility

source/reference/beta-program/destinationDataHandling.txt
- [DOCSP-45060-ignorePreExistingNamespaces-incompatibility (#500)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/500)
=> DOCSP-45060-ignorePreExistingNamespaces-incompatibility-v1.9-backport (500)

source/reference/beta-program/destinationDataHandling.txt
- [DOCSP-45060-ignorePreExistingNamespaces-incompatibility (#500)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/500)
=> DOCSP-45060-ignorePreExistingNamespaces-incompatibility-v1.8-backport (500)

source/includes/cluster-shutdown-warning.rst, source/reference/cutover-process.txt, source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-44528-cutover-failure-warnings (#485)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/485)
=> DOCSP-44528-cutover-failure-warnings-v1.9-backport (485)

source/includes/cluster-shutdown-warning.rst, source/reference/cutover-process.txt, source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-44528-cutover-failure-warnings (#485)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/485)
=> DOCSP-44528-cutover-failure-warnings-v1.8-backport (485)

source/includes/cluster-shutdown-warning.rst, source/reference/cutover-process.txt, source/reference/mongosync/mongosync-behavior.txt
Reverts mongodb/docs-cluster-to-cluster-sync#485
=> Revert "DOCSP-44528-cutover-failure-warnings"

source/includes/cluster-shutdown-warning.rst, source/reference/cutover-process.txt, source/reference/mongosync/mongosync-behavior.txt
Reverts mongodb/docs-cluster-to-cluster-sync#502
=> Revert "DOCSP-44528-cutover-failure-warnings-v1.8-backport (485)"

source/includes/cluster-shutdown-warning.rst, source/reference/cutover-process.txt, source/reference/mongosync/mongosync-behavior.txt
Reverts mongodb/docs-cluster-to-cluster-sync#501
=> Revert "DOCSP-44528-cutover-failure-warnings-v1.9-backport (485)"

source/about-mongosync.txt, source/reference/limitations.txt
Adds links and clarifications around when write blocking is needed
https://deploy-preview-489--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/#general-limitations
https://deploy-preview-489--docs-cluster-to-cluster-sync.netlify.app/about-mongosync/#finalize-sync
https://jira.mongodb.org/browse/DOCSP-43406
=> DOCSP-43406-write-blocking-limitation-clarification

source/about-mongosync.txt, source/reference/limitations.txt
- [DOCSP-43406-write-blocking-limitation-clarification (#489)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/489)
=> DOCSP-43406-write-blocking-limitation-clarification-v1.9-backport (489)

source/about-mongosync.txt, source/reference/limitations.txt
- [DOCSP-43406-write-blocking-limitation-clarification (#489)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/489)
=> DOCSP-43406-write-blocking-limitation-clarification-v1.8-backport (489)

source/reference/limitations.txt
Add an `important` admonition that clarifies that the limitations are still in effect even after pausing/stopping mongosync.
https://deploy-preview-505--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/#limitations
https://jira.mongodb.org/browse/DOCSP-45350
=> DOCSP-45350-mongosync-limitations-always-in-effect

source/reference/limitations.txt
- [DOCSP-45350-mongosync-limitations-always-in-effect (#505)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/505)
=> DOCSP-45350-mongosync-limitations-always-in-effect-v1.9-backport (505)

source/reference/limitations.txt
We're going to add a guardrail for this in [REP-5303](https://jira.mongodb.org/browse/REP-5303), but we should clarify it ahead of time in our General Limitations:
> `mongosync` does not support in-place server version upgrades that change the major or minor version during a migration. `mongosync` does allow patch version upgrades. See the [server upgrade instructions](https://www.mongodb.com/docs/manual/tutorial/upgrade-revision/) for more details.
=> (DOCSP-45638) [C2C] Add limitation for in-place major & minor server version upgrades

source/reference/limitations.txt
This will backport [(DOCSP-45638) [C2C] Add limitation for in-place major & minor server version upgrades (#519)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/519) to v1.8
We're going to add a guardrail for this in [REP-5303](https://jira.mongodb.org/browse/REP-5303), but we should clarify it ahead of time in our General Limitations:
> `mongosync` does not support in-place server version upgrades that change the major or minor version during a migration. `mongosync` does allow patch version upgrades. See the [server upgrade instructions](https://www.mongodb.com/docs/manual/tutorial/upgrade-revision/) for more details.
[DOCSP-45638](https://jira.mongodb.org/browse/DOCSP-45638)
=> (DOCSP-45638) [C2C] Backport to v1.8: Add limitation for in-place major & minor server version upgrades #519 #520

config/redirects, snooty.toml, source/includes/beta-program-intro.rst, source/includes/fact-verifier-limitations.rst, source/includes/opts/acceptDisclaimer.rst, source/reference.txt, source/reference/api/start.txt, source/reference/beta-program-private.txt, source/reference/beta-program-private/abc-migration.txt, source/reference/beta-program-private/destinationDataHandling.txt, source/reference/beta-program-private/document-filtering.txt, source/reference/beta-program-private/many-to-one.txt, source/reference/beta-program-private/namespace-remapping.txt, source/reference/beta-program-private/orr.txt, source/reference/configuration.txt, source/reference/mongosync.txt, source/release-notes/1.8.txt, source/release-notes/1.9.txt
- [DOCSP-45310-remove-beta (#513)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/513)
=> DOCSP-45310-remove-beta-v1.9-backport (513)

config/redirects, snooty.toml, source/includes/beta-program-intro.rst, source/reference.txt, source/reference/api/start.txt, source/reference/beta-program-private.txt, source/reference/beta-program-private/abc-migration.txt, source/reference/beta-program-private/destinationDataHandling.txt, source/reference/beta-program-private/document-filtering.txt, source/reference/beta-program-private/many-to-one.txt, source/reference/beta-program-private/namespace-remapping.txt, source/reference/beta-program-private/orr.txt, source/reference/configuration.txt, source/reference/mongosync.txt, source/release-notes/1.8.txt
- [DOCSP-45310-remove-beta (#513)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/513)
=> DOCSP-45310-remove-beta-v1.8-backport (513)

snooty.toml
Backport https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/523 to v1.8
Similarly to our disclaimer for [mongodump](https://www.mongodb.com/docs/database-tools/mongodump/#mongodump) and other database tools, we should add a disclaimer to mongosync that it is not supported with non-genuine mongodb.
[DOCSP-45695](https://jira.mongodb.org/browse/DOCSP-45695)
=> (DOCSP-45695) Backport to v1.8: [C2C] Add banner that mongosync is not supported with non-genuine MongoDB #523 #527

snooty.toml
Backport https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/523 to v1.9
Similarly to our disclaimer for [mongodump](https://www.mongodb.com/docs/database-tools/mongodump/#mongodump) and other database tools, we should add a disclaimer to mongosync that it is not supported with non-genuine mongodb.
[DOCSP-45695](https://jira.mongodb.org/browse/DOCSP-45695)
=> (DOCSP-45695) Backport to v1.9: [C2C] Add banner that mongosync is not supported with non-genuine MongoDB #523

source/reference/verification.txt
currently, we don't document how to verify that shard keys are migrated during a sync. that said, it is important that users do this, so it'd be great to add this note.
From [Felipe Gasper](https://jira.mongodb.org/secure/ViewProfile.jspa?name=felipe.gasper%40mongodb.com):
> To find a collection’s shard key, look in `config.collections` for a document whose _id is the namespace in question, then look at that document’s key. So to manually check shard keys, run such a query on both source & destination, and compare the results.
https://deploy-preview-526--docs-cluster-to-cluster-sync.netlify.app/reference/verification/
[DOCSP-45308](https://jira.mongodb.org/browse/DOCSP-45308)
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) …
=> (DOCSP-45308) [c2c] add note on how to verify shard keys

source/reference/verification.txt
Backports changes from https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/526 to v1.8. 
Also backports new table format without entry for embedded verifier, which was introduced in v1.9. Reformats page from Use Cases and Tasks sections into Tasks > Table of verification methods. 
https://deploy-preview-531--docs-cluster-to-cluster-sync.netlify.app/reference/verification/
[DOCSP-45308](https://jira.mongodb.org/browse/DOCSP-45308)
=> (DOCSP-45308) Backport to v1.8: [c2c] add note on how to verify shard keys #526

source/includes/fact-older-version-limitations.rst, source/reference/limitations.txt
- Documents limits of Older Version Support in C2C
https://deploy-preview-522--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/#pre-6.0-migrations
[DOCSP-45860](https://jira.mongodb.org/browse/DOCSP-45860)
=> DOCSP-45860-older-version-limitations

source/includes/cross-version-sync.rst, source/includes/fact-minimum-fcv.rst, source/includes/fact-version-compatibility.rst, source/reference/mongosync.txt, source/reference/supported-server-version.txt, source/release-notes/1.10.txt
- Update C2C Version Compatibility page to reflect older version support 
- Added minimum supported version table to document major versions, patch versions, and minimum fcv 
- Added 4.4 and 5.0 to source & destination cluster compatibility table
- [Version Compatibility](https://deploy-preview-518--docs-cluster-to-cluster-sync.netlify.app/reference/supported-server-version/)
- [1.10 release notes](https://deploy-preview-518--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.10/)
https://jira.mongodb.org/browse/DOCSP-45859
=> DOCSP-45859 Version Compatibility

source/includes/fact-verifier-limitations.rst, source/reference/api/start.txt, source/reference/mongosync/mongosync-behavior.txt, source/reference/verification.txt
Mongosync's embedded verifier now supports sharded clusters. 
https://jira.mongodb.org/browse/DOCSP-45326
https://deploy-preview-534--docs-cluster-to-cluster-sync.netlify.app/reference/verification/
https://deploy-preview-534--docs-cluster-to-cluster-sync.netlify.app/reference/verification/embedded/
https://deploy-preview-534--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/
https://deploy-preview-534--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/mongosync-behavior/
=> Remove mentions of embedded verifier not supporting sharded clusters

source/about-mongosync.txt, source/faq.txt, source/index.txt, source/reference/mongosync.txt, source/reference/mongosync/mongosync-behavior.txt
Update "Can I perform reads or writes to my destination cluster while mongosync is syncing?" [FAQ entry](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/faq/#can-i-perform-reads-or-writes-to-my-destination-cluster-while-mongosync-is-syncing-) to include the below context:
> mongosync combines and reorders writes from the source to destination during the sync, and also temporarily modifies various collection characteristics. As a result, the destination is not guaranteed to match the source, even a stale version of the source, at any point in time while the sync is still executing. The only way to ensure that the destination matches the source is to commit mongosync with writes paused on both source and destination. Upon commit, it is only safe to resume writes on the …
=> (DOCSP-45816) [C2C] Clarify documentations on continuous sync

source/about-mongosync.txt, source/faq.txt, source/index.txt, source/reference/mongosync.txt, source/reference/mongosync/mongosync-behavior.txt
- [(DOCSP-45816) [C2C] Clarify documentations on continuous sync (#532)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/532)
=> (DOCSP-45816)-Clarify-documentations-on-continuous-sync-v1.8-backport (532)

source/includes/example-filter-collection-with-renaming.rst, source/includes/fact-oplog-disk-storage.rst
- Adds note about the embedded verifier requiring a larger oplog. 
https://deploy-preview-536--docs-cluster-to-cluster-sync.netlify.app/reference/oplog-sizing/#considerations
https://jira.mongodb.org/browse/DOCSP-46282
=> DOCSP-46282-destination-oplog-size

source/includes/example-filter-collection-with-renaming.rst, source/includes/fact-oplog-disk-storage.rst
- [DOCSP-46282-destination-oplog-size (#536)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/536)
=> DOCSP-46282-destination-oplog-size-v1.9-backport (536)

source/about-mongosync.txt, source/faq.txt, source/index.txt, source/reference/mongosync.txt, source/reference/mongosync/mongosync-behavior.txt
- [(DOCSP-45816) [C2C] Clarify documentations on continuous sync (#532)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/532)
=> (DOCSP-45816)-Clarify-documentations-on-continuous-sync-v1.9-backport (532)

source/reference/verification.txt, source/reference/verification/verifier.txt
Removes the sentence stating migration verifier is unsupported/experimental, and bolds the sentence stating embedded verifier is a preferred method.
https://deploy-preview-537--docs-cluster-to-cluster-sync.netlify.app/reference/verification/#tasks
https://deploy-preview-537--docs-cluster-to-cluster-sync.netlify.app/reference/verification/verifier/#about-this-task
https://jira.mongodb.org/browse/DOCSP-46115
=> DOCSP-46115 removes mongosync caveat and highlights embedded verifier

source/reference/verification.txt, source/reference/verification/verifier.txt
- [DOCSP-46115 removes mongosync caveat and highlights embedded verifier (#537)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/537)
=> DOCSP-46115-removes-mongosync-caveat-and-highlights-embedded-verifier-v1.9-backport (537)

source/reference/verification.txt, source/reference/verification/verifier.txt
- [DOCSP-46115 removes mongosync caveat and highlights embedded verifier (#537)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/537)
=> DOCSP-46115-removes-mongosync-caveat-and-highlights-embedded-verifier-v1.8-backport (537)

source/faq.txt, source/reference/configuration.txt, source/reference/mongosync.txt
Per [this Slack thread](https://mongodb.slack.com/archives/C02SQPJHQ85/p1732128778430069), mongosync’s docs should specifically address mid-migration load level adjustments.
Suggested text:
> You can adjust mongosync’s load level during a migration. To do this, terminate all mongosync processes, then restart them with the needed load level. Mongosync will resume roughly where it was before you ended the earlier processes.
- This same procedure can be used to update any configuration setting other than --cluster0, --cluster1, and --id. To document this, I added a new section to the [Configuration](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/configuration/) reference page with directions on how to update configuration settings during an active sync. 
- Linked to …
=> (DOCSP-45558) [C2C] Mention altering load level during a migration in mongosync’s documentation.

source/reference/configuration.txt
[DOCSP-45558](https://jira.mongodb.org/browse/DOCSP-45558) introduced an 'Unknown interpreted text role "reF".' error from a capitalization error. This fixes that error, which was not backported into other C2C versions.
https://deploy-preview-548--docs-cluster-to-cluster-sync.netlify.app/reference/configuration/
[DOCSP-46441](https://jira.mongodb.org/browse/DOCSP-46441)
=> (DOCSP-46441) [C2C] Fix 'reF' typo in configuration page

source/faq.txt, source/reference/configuration.txt, source/reference/mongosync.txt
- [(DOCSP-45558) [C2C] Mention altering load level during a migration in mongosync’s documentation. (#530)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/530)
=> (DOCSP-45558)-Mention-altering-load-level-during-a-migration-in-mongosync’s-documentation-v1.8-backport (530)

source/faq.txt, source/reference/configuration.txt, source/reference/mongosync.txt
- [(DOCSP-45558) [C2C] Mention altering load level during a migration in mongosync’s documentation. (#530)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/530)
=> (DOCSP-45558)-Mention-altering-load-level-during-a-migration-in-mongosync’s-documentation-v1.9-backport (530)

source/reference/verification/embedded.txt
https://jira.mongodb.org/browse/DOCSP-46058
Clarifying small paragraph.
Staging: https://deploy-preview-544--docs-cluster-to-cluster-sync.netlify.app/reference/verification/embedded/#verification-checks
=> DOCSP-46058: Clarify docs for verification behavior during commit

source/reference/verification/embedded.txt
- [DOCSP-46058: Clarify docs for verification behavior during commit (#544)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/544)
=> DOCSP-46058-Clarify-docs-for-verification-behavior-during-commit-v1.9-backport (544)

source/includes/table-permissions-atlas.rst
- [DOCSP-46461-remove-backup-as-required-role (#551)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/551)
=> DOCSP-46461-remove-backup-as-required-role-v1.9-backport (551)

source/includes/table-permissions-atlas.rst
- [DOCSP-46461-remove-backup-as-required-role (#551)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/551)
=> DOCSP-46461-remove-backup-as-required-role-v1.8-backport (551)

source/includes/fact-verifier-unsupported.rst
https://jira.mongodb.org/browse/DOCSP-46039
Adds clarification about TTL indexes.
Staging: https://deploy-preview-545--docs-cluster-to-cluster-sync.netlify.app/reference/verification/embedded/#unsupported-verification-checks
=> DOCSP-46039: Clarify verifier limitation about TTLs

source/includes/fact-verifier-unsupported.rst
- [DOCSP-46039: Clarify verifier limitation about TTLs (#545)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/545)
=> DOCSP-46039-Clarify-verifier-limitation-about-TTLs-v1.9-backport (545)

source/includes/table-permissions-self-hosted.rst
removed the `backup` role from the self-managed clusters table (row: write-blocking, column: required destination permissions
https://deploy-preview-556--docs-cluster-to-cluster-sync.netlify.app/reference/permissions/
https://jira.mongodb.org/browse/DOCSP-46396
=> DOCSP-46396 removed backup

snooty.toml
- [DOCSP-46767-update-mongosync-nongenuine-note (#562)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/562)
=> DOCSP-46767-update-mongosync-nongenuine-note-v1.9-backport (562)

snooty.toml
- [DOCSP-46767-update-mongosync-nongenuine-note (#562)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/562)
=> DOCSP-46767-update-mongosync-nongenuine-note-v1.8-backport (562)

source/reference/api/reverse.txt, source/reference/api/start.txt, source/reference/permissions.txt, source/release-notes/1.10.txt, source/reverse-sync.txt
- Adds Pre-6.0 Migration section to User Permissions Page
- Documents limitation for reversing & write blocking under respective pages/entries
- [User Permissions](https://deploy-preview-552--docs-cluster-to-cluster-sync.netlify.app/reference/permissions/#pre-6.0-migrations)
- [Reverse limitation](https://deploy-preview-552--docs-cluster-to-cluster-sync.netlify.app/reference/api/reverse/#limitations)
- [Write blocking limitation](https://deploy-preview-552--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/#request:~:text=cluster%20accepts%20writes.-,IMPORTANT%3A%20If%20you%20are%20migrating%20from%20a%20pre%2D6.0%20source%20cluster%2C%20you%20cannot%20set%20enableUserWriteBlocking%20to%20true.,-To%20reverse%20sync)
- [Reversible …
=> DOCSP-45862 User permissions older version

source/includes/fact-verifier-limitations.rst, source/includes/table-permissions-atlas.rst, source/includes/table-permissions-self-hosted.rst, source/includes/verify-reversible-migrations.rst, source/reference/api/reverse.txt, source/reference/api/start.txt, source/release-notes/1.10.txt
https://jira.mongodb.org/browse/DOCSP-45965
Remove limitations on verifier not being enabled for reverse direction of reversible migration. Also adds permissions info.
Staging:
- https://deploy-preview-549--docs-cluster-to-cluster-sync.netlify.app/reference/api/reverse/#embedded-verifier
- https://deploy-preview-549--docs-cluster-to-cluster-sync.netlify.app/reference/verification/embedded/#limitations
- https://deploy-preview-549--docs-cluster-to-cluster-sync.netlify.app/reference/permissions/#self-managed-clusters
- https://deploy-preview-549--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.10/
- https://deploy-preview-549--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/#request-body-parameters
=> DOCSP-45965: Embedded Verifier: Verify Reversible Migrations

source/includes/fact-verifier-limitations.rst, source/reference/verification/embedded.txt
Adds a note that during pre-6.0 migrations, the verifier checks metadata and indexes _only_ for DDL events. 
- Opted to keep the previously documented limitations in their own section, remove the redundant note at the top of the page, and make the new functionality a note since it doesn't apply to all migrations.
https://deploy-preview-557--docs-cluster-to-cluster-sync.netlify.app/reference/verification/embedded/#unsupported-verification-checks
https://jira.mongodb.org/browse/DOCSP-45863
=> DOCSP-45863-embedded-verifier-migrations

source/includes/cross-version-sync.rst, source/includes/fact-minimum-fcv.rst, source/includes/fact-older-version-limitations.rst, source/includes/fact-pre-6.0-migration.rst, source/includes/fact-verifier-limitations.rst, source/includes/fact-version-compatibility.rst, source/includes/table-pre-6.0-compatibility.rst, source/reference/api/reverse.txt, source/reference/api/start.txt, source/reference/limitations.txt, source/reference/mongosync.txt, source/reference/permissions.txt, source/reference/supported-server-version.txt, source/reference/verification/embedded.txt, source/release-notes/1.10.txt, source/reverse-sync.txt
Merge `feature-older-version-support` feature branch 
https://jira.mongodb.org/browse/DOCSP-41415
=> DOCSP-41415 Merge Older Version Support Feature Branch

source/reference/cutover-process.txt
fixes typo on finalize cutover page
https://deploy-preview-568--docs-cluster-to-cluster-sync.netlify.app/reference/cutover-process/#verify-the-status-of-mongosync.
https://jira.mongodb.org/browse/DOCSP-46814
=> DOCSP-46814-finalize-cutover-typo

source/about-mongosync.txt, source/connecting.txt, source/connecting/atlas-to-atlas.txt, source/connecting/onprem-to-atlas.txt, source/connecting/onprem-to-onprem.txt, source/index.txt, source/installation.txt, source/quickstart.txt, source/reference/versioning.txt, source/release-notes.txt, source/release-notes/1.10.txt
- Removed `in development` banners from all applicable pages 
- Updated current stable release to 1.10
- [1.10 release notes](https://deploy-preview-570--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.10/#std-label-c2c-release-notes-1.10)
- [release notes (check current stable releases)](https://deploy-preview-570--docs-cluster-to-cluster-sync.netlify.app/release-notes/#release-notes)
- [about mongosync](https://deploy-preview-570--docs-cluster-to-cluster-sync.netlify.app/about-mongosync/)
- [connecting mongosync](https://deploy-preview-570--docs-cluster-to-cluster-sync.netlify.app/connecting/)
- [installation](https://deploy-preview-570--docs-cluster-to-cluster-sync.netlify.app/installation/)
- [quickstart](https://deploy-preview-570--docs-cluster-to-cluster-sync.netlify.app/qui …
=> DOCSP-46877 C2C 1.10 Release Tasks

source/reference/oplog-sizing.txt
- [DOCSP-46629-replSetResizeOplog-unsupported-Atlas (#558)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/558)
=> DOCSP-46629-replSetResizeOplog-unsupported-Atlas-v1.9-backport (558)

source/reference/oplog-sizing.txt
- [DOCSP-46629-replSetResizeOplog-unsupported-Atlas (#558)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/558)
=> DOCSP-46629-replSetResizeOplog-unsupported-Atlas-v1.8-backport (558)

source/includes/fact-verification-support-1.9.0.rst, source/includes/fact-verifier-limitations.rst, source/release-notes/1.9.txt
- [DOCSP-46038-1.9.0-verification (#578)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/578)
=> DOCSP-46038-1.9.0-verification-v1.10-backport (578)

source/includes/fact-verification-support-1.9.0.rst, source/includes/fact-verifier-limitations.rst, source/release-notes/1.9.txt
- [DOCSP-46038-1.9.0-verification (#578)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/578)
=> DOCSP-46038-1.9.0-verification-v1.9-backport (578)

source/reference/api/pause.txt, source/reference/mongosync/mongosync-behavior.txt
Adds information on when mongosync behavior during crashes or pauses
https://deploy-preview-577--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/mongosync-behavior/#interruptions-during-sync
https://deploy-preview-577--docs-cluster-to-cluster-sync.netlify.app/reference/api/pause/#behavior
https://jira.mongodb.org/browse/DOCSP-44803
=> DOCSP-44803-pause-and-crash-behavior

source/reference/api/pause.txt, source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-44803-pause-and-crash-behavior (#577)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/577)
=> DOCSP-44803-pause-and-crash-behavior-v1.8-backport (577)

source/faq.txt, source/includes/fact-older-version-limitations.rst, source/includes/fact-permissions-body.rst, source/includes/fact-write-blocking-enable.rst, source/includes/limitations-filtering.rst, source/includes/live-upgrade.rst, source/includes/table-permissions-atlas.rst, source/includes/table-permissions-self-hosted.rst, source/reference/api/commit.txt, source/reference/api/reverse.txt, source/reference/api/start.txt, source/reference/cutover-process.txt, source/reference/mongosync/mongosync-behavior.txt, source/reference/permissions.txt, source/reference/versioning.txt, source/release-notes.txt, source/release-notes/1.11.txt
https://jira.mongodb.org/browse/DOCSP-46893
Document: https://docs.google.com/document/d/1aGSzqekj5-ui8PZnem1ND_SV7__gYNfn64ROtELD4l4/edit?tab=t.0
Staging (search for "block" to narrow down changed sections):
- [FAQ](https://deploy-preview-581--docs-cluster-to-cluster-sync.netlify.app/faq/#can-i-perform-reads-or-writes-to-my-destination-cluster-while-mongosync-is-syncing-)
- [Filtering limitations](https://deploy-preview-581--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/#filtered-sync)
- [Pre-6.0 Limitations](https://deploy-preview-581--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/#pre-6.0-migrations)
- [Permissions page](https://deploy-preview-581--docs-cluster-to-cluster-sync.netlify.app/reference/permissions/) (intro, title change on tables, …
=> DOCSP-46893: Destination-only Write-blocking

.backportrc.json, snooty.toml, source/release-notes/1.11.txt
- Updates 1.11 release notes 
- Update backport script to include 1.11 (in preparation for 1.12 version bump) 
**NOTE:** Destination-only write blocking as a new feature will be documented in #581 and added to the release notes there.
https://deploy-preview-585--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.11/
https://jira.mongodb.org/browse/DOCSP-46895
=> DOCSP-46895 1.11 Release Notes

source/faq.txt, source/reference/api/start.txt
Adds an FAQ entry explaining why destination indexes may be larger than source indexes, and how to mitigate.
[FAQ: Why are the destination cluster indexes larger than the source cluster indexes?](https://deploy-preview-579--docs-cluster-to-cluster-sync.netlify.app/faq/#why-are-the-destination-cluster-indexes-larger-than-the-source-cluster-indexes-)
https://jira.mongodb.org/browse/DOCSP-46973
=> DOCSP-46973-adds-large-destination-index-FAQ

source/faq.txt, source/reference/api/start.txt
- [DOCSP-46973-adds-large-destination-index-FAQ (#579)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/579)
=> DOCSP-46973-adds-large-destination-index-FAQ-v1.8-backport (579)

source/faq.txt, source/reference/api/start.txt
- [DOCSP-46973-adds-large-destination-index-FAQ (#579)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/579)
=> DOCSP-46973-adds-large-destination-index-FAQ-v1.10-backport (579)

snooty.toml, source/reference/c2c-migrate-pqs.txt, source/reference/cutover-process.txt
Tutorial for manually migration persistent query settings
https://deploy-preview-580--docs-cluster-to-cluster-sync.netlify.app/reference/c2c-migrate-pqs/
https://deploy-preview-580--docs-cluster-to-cluster-sync.netlify.app/reference/cutover-process/#send-a-commit-request-to-mongosync.
https://jira.mongodb.org/browse/DOCSP-46854
=> DOCSP-46854-migrate-pqs-tutorial

snooty.toml, source/reference/c2c-migrate-pqs.txt, source/reference/cutover-process.txt
- [DOCSP-46854-migrate-pqs-tutorial (#580)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/580)
=> DOCSP-46854-migrate-pqs-tutorial-v1.10-backport (580)

snooty.toml, source/reference/c2c-migrate-pqs.txt, source/reference/cutover-process.txt
- [DOCSP-46854-migrate-pqs-tutorial (#580)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/580)
=> DOCSP-46854-migrate-pqs-tutorial-v1.9-backport (580)

snooty.toml, source/reference/c2c-migrate-pqs.txt, source/reference/cutover-process.txt
- [DOCSP-46854-migrate-pqs-tutorial (#580)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/580)
=> DOCSP-46854-migrate-pqs-tutorial-v1.8-backport (580)

source/reference/cutover-process.txt
https://jira.mongodb.org/browse/DOCSP-47159
Staging:
https://deploy-preview-599--docs-cluster-to-cluster-sync.netlify.app/reference/cutover-process/#if-you-manually-blocked-writes-on-the-destination-cluster-by-using---enable-application-writes-on-the-destination-cluster.
=> DOCSP-47159: Clarify write blocking recommendation on finalize cutover page

source/includes/fact-oplog-background.rst
Edited includes file about oplog. Removed outdated paragraph and added that the operations are applied after the collection copy phase. 
-[Oplog sizing page](https://deploy-preview-609--docs-cluster-to-cluster-sync.netlify.app/reference/oplog-sizing/)
-[FAQ page](https://deploy-preview-609--docs-cluster-to-cluster-sync.netlify.app/faq/#should-i-increase-the-size-of-the-oplog-in-the-source-cluster-)
https://jira.mongodb.org/browse/DOCSP-47126
- [] Does each file have 3-5 taxonomy facet tags?
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+Mon …
=> DOCSP-47126 edited oplog background fact

source/reference/beta-program-private/many-to-one.txt
Add necessary parameter to start many-to-one [migration](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/beta-program-private/many-to-one/#std-label-c2c-beta-many-to-one). 
https://deploy-preview-598--docs-cluster-to-cluster-sync.netlify.app/reference/beta-program-private/many-to-one/#std-label-c2c-beta-many-to-one
https://jira.mongodb.org/browse/DOCSP-46986
=> DOCSP-46986-destinationDataHandling-note

source/reference/beta-program-private/many-to-one.txt
- [DOCSP-46986-destinationDataHandling-note (#598)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/598)
=> DOCSP-46986-destinationDataHandling-note-v1.11-backport (598)

source/reference/beta-program-private/many-to-one.txt
- [DOCSP-46986-destinationDataHandling-note (#598)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/598)
=> DOCSP-46986-destinationDataHandling-note-v1.10-backport (598)

source/reference/beta-program-private/many-to-one.txt
- [DOCSP-46986-destinationDataHandling-note (#598)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/598)
=> DOCSP-46986-destinationDataHandling-note-v1.9-backport (598)

source/reference/beta-program-private/many-to-one.txt
- [DOCSP-46986-destinationDataHandling-note (#598)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/598)
=> DOCSP-46986-destinationDataHandling-note-v1.8-backport (598)

source/about-mongosync.txt, source/includes/fact-older-version-limitations.rst, source/includes/fact-write-blocking-enable.rst, source/includes/live-upgrade.rst, source/reference/api/reverse.txt, source/reference/api/start.txt, source/reference/cutover-process.txt, source/reference/limitations.txt, source/reference/versioning.txt, source/release-notes.txt, source/release-notes/1.12.txt, source/reverse-sync.txt, source/topologies/multiple-mongosyncs.txt
Adds `enableUserWriteBlocking` params and disallows live upgrade to 1.12. Also updates most mentions of `enableUserWriteBlocking` params to use the strings.
https://jira.mongodb.org/browse/DOCSP-47288
Staging:
- https://deploy-preview-611--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/#request-body-parameters
- https://deploy-preview-611--docs-cluster-to-cluster-sync.netlify.app/reference/versioning/#live-upgrade
- https://deploy-preview-611--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.12/
=> DOCSP-47288: Rename some `enableUserWriteBlocking` internal-only options and disallow live upgrade to 1.12

source/reference/cutover-process.txt
=> DOCSP-45442 (#621)

source/includes/fact-verifier-limitations.rst, source/reference/api/progress.txt, source/reference/live-upgrade.txt, source/reference/versioning.txt, source/release-notes/1.11.txt, source/release-notes/1.7.txt
Remove mentions of live upgrades
https://deploy-preview-628--docs-cluster-to-cluster-sync.netlify.app/reference/versioning/
https://deploy-preview-628--docs-cluster-to-cluster-sync.netlify.app/reference/api/progress/#behavior
https://deploy-preview-628--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.11/#live-upgrades
https://deploy-preview-628--docs-cluster-to-cluster-sync.netlify.app/reference/live-upgrade/#std-label-c2c-live-upgrade
https://jira.mongodb.org/browse/DOCSP-47695
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoD …
=> DOCSP-47695-remove-live-upgrade

source/includes/fact-verifier-limitations.rst, source/reference/api/progress.txt, source/reference/live-upgrade.txt, source/reference/versioning.txt, source/release-notes/1.11.txt, source/release-notes/1.7.txt
- [DOCSP-47695-remove-live-upgrade (#628)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/628)
=> DOCSP-47695-remove-live-upgrade-v1.11-backport (628)

source/includes/fact-minimum-server-version-support.rst, source/reference/mongosync.txt
Replaces outdated information on minimum supported versions with link to the [MongoDB Server Version Compatibility](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/supported-server-version/) document.
Removed text: 
> The minimum supported server versions of MongoDB are 6.0.17 and 7.0.13.
> You can migrate data on clusters (source) with versions of MongoDB lower than 6.0 to an Atlas cluster (destination). Migration from clusters with lower version requires additional preparation and configuration in the clusters with the lower version. Contact your account team to inquire about Professional Services.
https://deploy-preview-643--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/#compatibility
https://jira.mongodb.org/browse/DOCSP-48043
=> replace-outdated-blurb-w-link-to-versions-file

source/includes/fact-oplog-disk-storage.rst, source/release-notes/1.12.txt
Remove admonition within admonition in [quickstart page. ](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/quickstart/)
- https://deploy-preview-646--docs-cluster-to-cluster-sync.netlify.app/quickstart/#define-a-source-and-a-destination-cluster
- https://deploy-preview-646--docs-cluster-to-cluster-sync.netlify.app/faq/#what-hardware-specifications-should-the-destination-cluster-have-
- https://deploy-preview-646--docs-cluster-to-cluster-sync.netlify.app/reference/oplog-sizing/#considerations
https://jira.mongodb.org/browse/DOCSP-48145
[What's expected of an external …
=> DOCSP-48145-quickstart-nested-components

source/includes/fact-oplog-disk-storage.rst
- [DOCSP-48145-quickstart-nested-components (#646)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/646)
=> DOCSP-48145-quickstart-nested-components-v1.10-backport (646)

source/includes/fact-oplog-disk-storage.rst
- [DOCSP-48145-quickstart-nested-components (#646)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/646)
=> DOCSP-48145-quickstart-nested-components-v1.9-backport (646)

source/includes/fact-minimum-server-version-support.rst, source/reference/mongosync.txt
- [DOCSP-48043replace-outdated-blurb-w-link-to-versions-file (#643)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/643)
=> DOCSP-48043-replace-outdated-blurb-w-link-to-versions-file-v1.11-backport (643)

source/includes/fact-minimum-server-version-support.rst, source/reference/mongosync.txt
- [DOCSP-48043replace-outdated-blurb-w-link-to-versions-file (#643)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/643)
=> DOCSP-48043-replace-outdated-blurb-w-link-to-versions-file-v1.10-backport (643)

source/includes/minimum-destination-privileges.rst, source/includes/minimum-source-privileges.rst, source/reference/permissions.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-47109
Staging: https://deploy-preview-650--docs-cluster-to-cluster-sync.netlify.app/reference/permissions/
=> DOCSP-47109-document-minimum-privileges

source/includes/minimum-destination-privileges.rst, source/includes/minimum-source-privileges.rst, source/reference/permissions.txt
- [DOCSP-47109-document-minimum-privileges (#650)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/650)
=> DOCSP-47109-document-minimum-privileges-v1.11-backport (650)

source/includes/minimum-destination-privileges.rst, source/includes/minimum-source-privileges.rst, source/reference/permissions.txt
- [DOCSP-47109-document-minimum-privileges (#650)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/650)
=> DOCSP-47109-document-minimum-privileges-v1.10-backport (650)

source/reference/mongosync/mongosync-behavior.txt
Add info to [mongosync behavior page](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/mongosync/mongosync-behavior/#embedded-verifier-disclaimer) ab metadata databases created during migration. 
https://deploy-preview-651--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/mongosync-behavior/#mongosync-metadata
https://jira.mongodb.org/browse/DOCSP-48242
=> DOCSP-48242-mongosync-metadata-post-sync

source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-48242-mongosync-metadata-post-sync (#651)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/651)
=> DOCSP-48242-mongosync-metadata-post-sync-v1.11-backport (651)

source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-48242-mongosync-metadata-post-sync (#651)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/651)
=> DOCSP-48242-mongosync-metadata-post-sync-v1.9-backport (651)

source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-48242-mongosync-metadata-post-sync (#651)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/651)
=> DOCSP-48242-mongosync-metadata-post-sync-v1.8-backport (651)

source/includes/table-permissions-atlas.rst
- [DOCSP-48417-writeBlocking-permission-typo (#658)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/658)
=> DOCSP-48417-writeBlocking-permission-typo-v1.11-backport (658)

source/includes/table-permissions-atlas.rst
- [DOCSP-48417-writeBlocking-permission-typo (#658)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/658)
=> DOCSP-48417-writeBlocking-permission-typo-v1.10-backport (658)

source/includes/table-permissions-atlas.rst
- [DOCSP-48417-writeBlocking-permission-typo (#658)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/658)
=> DOCSP-48417-writeBlocking-permission-typo-v1.9-backport (658)

source/includes/table-permissions-atlas.rst
- [DOCSP-48417-writeBlocking-permission-typo (#658)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/658)
=> DOCSP-48417-writeBlocking-permission-typo-v1.8-backport (658)

source/includes/api/requests/start-rs-shard.sh
Fix syntax error on [start page. ](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/api/start/#start-sync-from-replica-set-to-sharded-cluster)
https://deploy-preview-664--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/#start-sync-from-replica-set-to-sharded-cluster
https://jira.mongodb.org/browse/DOCSP-48399
=> DOCSP-48399-start-sync-syntax-error

source/includes/api/requests/start-rs-shard.sh
- [DOCSP-48399-start-sync-syntax-error (#664)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/664)
=> DOCSP-48399-start-sync-syntax-error-v1.11-backport (664)

source/includes/api/requests/start-rs-shard.sh
- [DOCSP-48399-start-sync-syntax-error (#664)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/664)
=> DOCSP-48399-start-sync-syntax-error-v1.10-backport (664)

source/includes/api/requests/start-rs-shard.sh
- [DOCSP-48399-start-sync-syntax-error (#664)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/664)
=> DOCSP-48399-start-sync-syntax-error-v1.9-backport (664)

source/includes/api/requests/start-rs-shard.sh, source/reference/beta-program-private/orr.txt
- [DOCSP-48399-start-sync-syntax-error (#664)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/664)
=> DOCSP-48399-v1.8-backport

source/reference/api/start.txt
- [DOCSP-48393-reorder-shardingEntries-note (#672)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/672)
=> DOCSP-48393-reorder-shardingEntries-note-v1.11-backport (672)

source/reference/api/start.txt
- [DOCSP-48393-reorder-shardingEntries-note (#672)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/672)
=> DOCSP-48393-reorder-shardingEntries-note-v1.10-backport (672)

source/reference/api/start.txt
- [DOCSP-48393-reorder-shardingEntries-note (#672)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/672)
=> DOCSP-48393-reorder-shardingEntries-note-v1.9-backport (672)

source/reference/api/start.txt
- [DOCSP-48393-reorder-shardingEntries-note (#672)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/672)
=> DOCSP-48393-reorder-shardingEntries-note-v1.8-backport (672)

source/includes/api/tables/progress-response.rst, source/reference/api/commit.txt
Clarifies that there are 3 diff `lagTimeSeconds` fields in the `progress` response in the [progress page](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/api/progress/#std-label-c2c-api-progress) & [commit page](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/api/commit/). 
- https://deploy-preview-673--docs-cluster-to-cluster-sync.netlify.app/reference/api/progress/#std-label-c2c-api-progress
- https://deploy-preview-673--docs-cluster-to-cluster-sync.netlify.app/reference/api/commit/
https://jira.mongodb.org/browse/DOCSP-48421
[What's expected of an external …
=> DOCSP-48421-clarify-verifier-lag-time

source/includes/api/tables/progress-response.rst, source/reference/api/commit.txt
- [DOCSP-48421-clarify-verifier-lag-time (#673)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/673)
=> DOCSP-48421-clarify-verifier-lag-time-v1.11-backport (673)

source/includes/api/tables/progress-response.rst, source/reference/api/commit.txt
- [DOCSP-48421-clarify-verifier-lag-time (#673)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/673)
=> DOCSP-48421-clarify-verifier-lag-time-v1.10-backport (673)

source/includes/api/tables/progress-response.rst, source/reference/api/commit.txt
- [DOCSP-48421-clarify-verifier-lag-time (#673)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/673)
=> DOCSP-48421-clarify-verifier-lag-time-v1.9-backport (673)

source/reference/versioning.txt
Add note to 1.13 C2C mongosync versioning page that in 1.13, live updating is supported for 1.12 -> 1.13. 
https://deploy-preview-681--docs-cluster-to-cluster-sync.netlify.app/reference/versioning/#upgrade-or-downgrade
https://jira.mongodb.org/browse/DOCSP-48369
=> DOCSP-48369-mongosync-version-bump-1.13

source/about-mongosync.txt, source/faq.txt, source/includes/fact-no-mongosync-disaster-recovery.rst, source/index.txt, source/quickstart.txt, source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-48525-disaster-recovery-faq-entry (#679)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/679)
=> DOCSP-48525-disaster-recovery-faq-entry-v1.10-backport (679)

source/about-mongosync.txt, source/faq.txt, source/includes/fact-no-mongosync-disaster-recovery.rst, source/index.txt, source/quickstart.txt, source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-48525-disaster-recovery-faq-entry (#679)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/679)
=> DOCSP-48525-disaster-recovery-faq-entry-v1.9-backport (679)

source/includes/fact-mongosync-balancer.rst, source/reference/limitations.txt, source/reference/mongosync/mongosync-behavior.txt
https://jira.mongodb.org/browse/DOCSP-46644
Staging:
- https://deploy-preview-670--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/mongosync-behavior/#sharded-clusters
- https://deploy-preview-670--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/#sharded-clusters
=> DOCSP-46644: Stop balancer on a per-collection basis

snooty.toml, source/includes/verification-gpg-results.rst, source/includes/verify-signatures-before-you-begin.rst, source/includes/verify-signatures-intro.rst, source/installation.txt, source/installation/verify.txt, source/installation/verify/gpg.txt, source/installation/verify/macos.txt, source/installation/verify/rpm.txt
- [DOCSP-40664-verify-signature (#686)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/686)
=> DOCSP-40664-verify-signature-v1.8-backport (686)

snooty.toml, source/includes/verification-gpg-results.rst, source/includes/verify-signatures-before-you-begin.rst, source/includes/verify-signatures-intro.rst, source/installation.txt, source/installation/verify.txt, source/installation/verify/gpg.txt, source/installation/verify/macos.txt, source/installation/verify/rpm.txt
- [DOCSP-40664-verify-signature (#686)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/686)
=> DOCSP-40664-verify-signature-v1.9-backport (686)

snooty.toml, source/includes/verification-gpg-results.rst, source/includes/verify-signatures-before-you-begin.rst, source/includes/verify-signatures-intro.rst, source/installation.txt, source/installation/verify.txt, source/installation/verify/gpg.txt, source/installation/verify/macos.txt, source/installation/verify/rpm.txt
- [DOCSP-40664-verify-signature (#686)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/686)
=> DOCSP-40664-verify-signature-v1.11-backport (686)

snooty.toml, source/installation/install-on-linux.txt, source/release-notes.txt, source/release-notes/1.13.txt
mongosync 1.13 release notes. See [release notes document](https://docs.google.com/document/d/1QWu7uJgroWtSl449ccAHLFLH4XFppK6reJUwoxsADqE/edit?tab=t.vaydpds4piio#heading=h.vgunpraikhpo).
- [Release Notes](https://deploy-preview-680--docs-cluster-to-cluster-sync.netlify.app/release-notes/#release-notes)
- [Release Notes for mongosync 1.13](https://deploy-preview-680--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.13/#std-label-c2c-release-notes-1.13)
- [Linux Supported Platforms](https://deploy-preview-680--docs-cluster-to-cluster-sync.netlify.app/installation/install-on-linux/#platform-support)
https://jira.mongodb.org/browse/DOCSP-48354
=> DOCSP-48354-1.13-release-notes

source/reference/mongosync/mongosync-behavior.txt
https://jira.mongodb.org/browse/DOCSP-48515
Staging: https://deploy-preview-678--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/mongosync-behavior/#chunk-distribution
=> DOCSP-48515: Source/destination balancing

source/reference/limitations.txt, source/reference/mongosync/mongosync-behavior.txt
https://deploy-preview-691--docs-cluster-to-cluster-sync.netlify.app/reference/mongosync/mongosync-behavior/#embedded-config-server-shards
https://deploy-preview-691--docs-cluster-to-cluster-sync.netlify.app/reference/limitations/#sharded-clusters
https://jira.mongodb.org/browse/DOCSP-48609
=> DOCSP-48609-add-mongosync-notes

source/reference/limitations.txt, source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-48609-add-mongosync-notes (#691)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/691)
=> DOCSP-48609-add-mongosync-notes-v1.11-backport (691)

source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-48515: Source/destination balancing (#678)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/678)
=> DOCSP-48515-Source-destination-balancing-v1.11-backport (678)

source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-48515: Source/destination balancing (#678)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/678)
=> DOCSP-48515-Source-destination-balancing-v1.10-backport (678)

source/reference/mongosync/mongosync-behavior.txt
- [DOCSP-48515: Source/destination balancing (#678)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/678)
=> DOCSP-48515-Source-destination-balancing-v1.8-backport (678)

source/reference/live-upgrade.txt
Fix inaccurate wording.
Backport to prev versions (1.11?)
https://deploy-preview-698--docs-cluster-to-cluster-sync.netlify.app/reference/live-upgrade/
https://jira.mongodb.org/browse/DOCSP-48662
=> DOCSP-48662: Fix inaccurate wording on Live Upgrades notice

source/reference/live-upgrade.txt
- [DOCSP-48662: Fix inaccurate wording on Live Upgrades notice (#698)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/698)
=> DOCSP-48662-Fix-inaccurate-wording-on-Live-Upgrades-notice-v1.11-backport (698)

source/reference/verification/embedded.txt, source/release-notes/1.10.txt
Backport to 1.10
Clarifies that embedded verifier is on by default for sharded clusters.
https://jira.mongodb.org/browse/DOCSP-48653
- https://deploy-preview-696--docs-cluster-to-cluster-sync.netlify.app/reference/verification/embedded/
- https://deploy-preview-696--docs-cluster-to-cluster-sync.netlify.app/release-notes/1.10/#upgrades-to-embedded-verifier
=> DOCSP-48653: Make it clear the embedded verifier is on by default for sharded clusters

source/reference/verification/embedded.txt, source/release-notes/1.10.txt
- [DOCSP-48653: Make it clear the embedded verifier is on by default for sharded clusters (#696)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/696)
=> DOCSP-48653-Make-it-clear-the-embedded-verifier-is-on-by-default-for-sharded-clusters-v1.11-backport (696)

source/reference/verification/embedded.txt, source/release-notes/1.10.txt
- [DOCSP-48653: Make it clear the embedded verifier is on by default for sharded clusters (#696)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/696)
=> DOCSP-48653-Make-it-clear-the-embedded-verifier-is-on-by-default-for-sharded-clusters-v1.10-backport (696)

source/reference/verification/embedded.txt, source/release-notes/1.10.txt
- [DOCSP-48653: Make it clear the embedded verifier is on by default for sharded clusters (#696)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/696)
=> DOCSP-48653-Make-it-clear-the-embedded-verifier-is-on-by-default-for-sharded-clusters-v1.12-backport (696)

source/reference/live-upgrade.txt
- [remove blurb (#716)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/716)
=> DOCSP-48963-remove-live-upgrade-blurb-v1.13-backport (716)

source/includes/api/requests/start-reversible.sh, source/reference/api/start.txt, source/reference/cutover-process.txt, source/topologies/multiple-mongosyncs.txt
Updates outdated use of enableUserWriteBlocking from "true" and "false" to "enableUserWriteBlocking" and "none"
https://deploy-preview-718--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/
https://deploy-preview-718--docs-cluster-to-cluster-sync.netlify.app/reference/cutover-process/#send-a-commit-request-to-mongosync.
https://deploy-preview-718--docs-cluster-to-cluster-sync.netlify.app/topologies/multiple-mongosyncs/#start-multiple-mongosync-instances
https://jira.mongodb.org/browse/DOCSP-47851
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guid …
=> DOCSP-47851-update-enableUserWriteBlocking-values

source/includes/api/requests/start-reversible.sh, source/reference/api/start.txt, source/reference/cutover-process.txt, source/topologies/multiple-mongosyncs.txt
- [DOCSP-47851-update-enableUserWriteBlocking-values (#718)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/718)
=> DOCSP-47851-update-enableUserWriteBlocking-values-v1.12-backport (718)

source/includes/api/requests/start-reversible.sh, source/reference/api/start.txt, source/reference/cutover-process.txt, source/topologies/multiple-mongosyncs.txt
- [DOCSP-47851-update-enableUserWriteBlocking-values (#718)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/718)
=> DOCSP-47851-update-enableUserWriteBlocking-values-v1.13-backport (718)

source/connecting/onprem-to-atlas.txt, source/includes/table-permissions-atlas-onprem-to-atlas.rst, source/includes/table-permissions-atlas.rst, source/includes/table-permissions-self-hosted-onprem-to-atlas.rst
Updates table based on ticket feedback to list the correct permissions
https://deploy-preview-719--docs-cluster-to-cluster-sync.netlify.app/connecting/onprem-to-atlas/
https://jira.mongodb.org/browse/DOCSP-48735
=> DOCSP-48735-clarify-required-permissions

source/connecting/onprem-to-atlas.txt, source/includes/table-permissions-atlas-onprem-to-atlas.rst, source/includes/table-permissions-self-hosted-onprem-to-atlas.rst
- [DOCSP-48735-clarify-required-permissions (#719)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/719)
=> DOCSP-48735-clarify-required-permissions-v1.13-backport (719)

source/connecting/onprem-to-atlas.txt, source/includes/table-permissions-atlas-onprem-to-atlas.rst, source/includes/table-permissions-self-hosted-onprem-to-atlas.rst
- [DOCSP-48735-clarify-required-permissions (#719)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/719)
=> DOCSP-48735-clarify-required-permissions-v1.12-backport (719)

source/connecting/onprem-to-atlas.txt, source/includes/table-permissions-atlas-onprem-to-atlas.rst, source/includes/table-permissions-self-hosted-onprem-to-atlas.rst
- [DOCSP-48735-clarify-required-permissions (#719)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/719)
=> DOCSP-48735-clarify-required-permissions-v1.11-backport (719)

source/reference/supported-server-version.txt
- [change version (#715)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/715)
=> DOCSP-48987-update-server-compat-v1.11-backport (715)

source/reference/api/start.txt
Clarify warning for manually building indexes on the destination cluster
https://deploy-preview-733--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/
https://jira.mongodb.org/browse/DOCSP-49351
=> DOCSP-49351-clarify-warning

source/reference/api/start.txt
- [change warning (#733)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/733)
=> DOCSP-49351-clarify-warning-v1.11-backport (733)

source/reference/api/start.txt
- [change warning (#733)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/733)
=> DOCSP-49351-clarify-warning-v1.12-backport (733)

source/reference/api/start.txt
- [change warning (#733)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/733)
=> DOCSP-49351-clarify-warning-v1.13-backport (733)

source/reference/collection-level-filtering.txt, source/reference/collection-level-filtering/filter-regex.txt
Adds details on regex syntax in c2c
https://deploy-preview-731--docs-cluster-to-cluster-sync.netlify.app/reference/collection-level-filtering/
https://deploy-preview-731--docs-cluster-to-cluster-sync.netlify.app/reference/collection-level-filtering/filter-regex/
https://jira.mongodb.org/browse/DOCSP-37757
=> DOCSP-37757-add-regex-info

source/reference/collection-level-filtering.txt, source/reference/collection-level-filtering/filter-regex.txt
- [DOCSP-37757-add-regex-info (#731)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/731)
=> DOCSP-37757-add-regex-info-v1.13-backport (731)

source/reference/collection-level-filtering.txt, source/reference/collection-level-filtering/filter-regex.txt
- [DOCSP-37757-add-regex-info (#731)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/731)
=> DOCSP-37757-add-regex-info-v1.12-backport (731)

source/reference/collection-level-filtering.txt, source/reference/collection-level-filtering/filter-regex.txt
- [DOCSP-37757-add-regex-info (#731)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/731)
=> DOCSP-37757-add-regex-info-v1.11-backport (731)

source/includes/api/facts/reverse-sync-requirements.rst, source/includes/api/facts/reverse-sync.rst, source/includes/fact-permissions-body.rst, source/reference/api/start.txt
Includes reference to the need of having the `restore` role assigned to the mongosync user for reverse sync operations in the [reference/api/start](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/api/start/) endpoint document.
It also includes a link to the [User Permissions](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/permissions/) page in the [reference/api/reverse](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/api/reverse/) endpoint document.
https://jira.mongodb.org/browse/DOCSP-32849
`start` endpoint:
https://deploy-preview-737--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/
`reverse` endpoint:
https://deploy-preview-737--docs-cluster-to-cluster-sync.netlify.app/reference/api/reverse/#requirement …
=> DOCSP-32849-add-reference-to-restore-role

source/includes/intro-start-api-example-intro.rst, source/reference/api/start.txt
Adds details on shard key in mongosync api example
https://deploy-preview-732--docs-cluster-to-cluster-sync.netlify.app/reference/api/start/
https://jira.mongodb.org/browse/DOCSP-48400
=> DOCSP-48400-confusion-multi-shard-key

source/includes/intro-start-api-example-intro.rst, source/reference/api/start.txt
- [DOCSP-48400-confusion-multi-shard-key (#732)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/732)
=> DOCSP-48400-confusion-multi-shard-key-v1.12-backport (732)

source/includes/intro-start-api-example-intro.rst, source/reference/api/start.txt
- [DOCSP-48400-confusion-multi-shard-key (#732)](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/732)
=> DOCSP-48400-confusion-multi-shard-key-v1.11-backport (732)
